/* Progressão, investigação e consequências. Sem dependências externas. */
(function(root){
'use strict';
const G=root.GameStory||(typeof require==='function'?require('./story.js'):null),M=root.GameWorld||(typeof require==='function'?require('./world.js'):null);
const C=(label,to,effect={},response='',hint='',requires=null)=>({label,to,effect,response,note:hint,hint,requires});
function scene(id,title,who,target,act,text,choices,objective){G.scenes[id]={title,place:M.roomAt(M.positions[target].x,M.positions[target].y),speaker:who,act,text,choices};M.stages[id]=[target,objective,title];}
function flag(s,k){return !!s.flags[k];}
const item=(s,name)=>s.inventory.includes(name);
const init=G.initial;G.initial=()=>({...init(),revision:3,events:[]});
const chapters=['I · O nome que falta','II · Seguir as provas','III · O preço da confiança','IV · Portas e promessas','V · Antes do amanhecer'];
const early=['prologo','quarto','altar','recusa','mira','noah','segredo'];early.forEach(id=>{G.scenes[id].act=0;});
// O vínculo é construído antes de a investigação começar.
G.scenes.mira.choices[0].label='“Não vou entregar o que você disser.”';
G.scenes.mira.choices[0].response='Mira espera o vigia passar. — Então observe antes de perguntar. Tomas tinha um cobertor azul. O beliche dele está vazio, mas a chamada ainda tem o nome. Eron viu quem levou as coisas. Procure-o depois de falar com Noah; ele controla a lista do dormitório.';
G.scenes.mira.choices[0].note='Mira confia mais em você. A ausência de Tomas virou uma pista.';
G.scenes.mira.choices[1].response='Mira recolhe a caneca. — Então pergunte ao Noah por que a lista dele ainda tem o nome de Tomas. Eu não vou dar mais nomes a ninguém.';
G.scenes.mira.choices[2].response='Mira olha para a câmera. — Quer uma resposta aqui? Procure a cama vazia. Depois fale com Eron. Não grite o nome dele também.';
G.scenes.noah.text.push('— Onde está Tomas? — pergunta Kali.\n— Transferido. É o que está na lista.\n— Para onde?\nNoah alisa o papel. — Não cuido dessa parte.\nNo dormitório, Eron faz um sinal para Kali esperar. Ele ouviu a resposta.');
for(const id of ['noah','segredo'])for(const c of G.choices({...G.initial(),scene:id}))if(c.to==='desaparecimento')c.response=(c.response||'')+'\nEron espera junto ao armário do dormitório. Ele viu a retirada das coisas de Tomas.';
const point=(x,y)=>M.authoredPoint(x,y);
Object.assign(M.positions,{tomasBed:point(7.3,7.8),ledger:point(29,5.8),box:point(54,27.8),tools:point(43,27),watch:point(39.5,23.2),cellDoor:point(53,14.9),keyDesk:point(38,38.8),records:point(50,38.7),tomas:point(57.5,7.5),meeting:point(48,28.5),signal:point(52,28.5),exitLatch:point(56,18.2),climax:point(45.5,17.5),escapeTurn:point(52,17.5),bread:point(41,27),cover:point(17.6,6.1)});
scene('desaparecimento','O que tiraram do quarto','eron','eronDorm',1,[
'— Não levaram só Tomas — Eron diz. — Levaram a coberta, a caneca e a caixa dele. Querem que a cama pareça vazia há semanas.',
'— Você viu para onde?\n— A caixa foi para a cozinha. Mas não vou seguir você até lá sem saber se consigo confiar. Primeiro procure debaixo do colchão dele. Depois compare com o registro na sala de leitura.',
'Um vigia entra para conferir as camas. Eron ainda segura a colher com que levantou a tábua do beliche.'],[
 C('Dizer que a colher é sua.','vestigios',{eron:2,flags:{protectedEron:true}},'— Caiu da minha bandeja.\nO vigia manda Kali guardá-la. Eron encosta dois dedos na madeira: um agradecimento sem som.','Eron +2 · você protegeu a investigação.'),
 C('Pedir que Eron guarde a colher, em voz baixa.','vestigios',{},'Eron esconde a colher. — A terceira costura do colchão. Não encoste na primeira. É a que eles verificam.','Você recebe a pista, mas ainda não conquistou um aliado.'),
 C('Perguntar ao vigia por que apagaram Tomas.','vestigios',{suspicion:2,eron:-1},'— Ele foi transferido. Arrume a cama.\nEron espera o adulto sair. — Agora ele sabe que estamos procurando.','Vigilância +2 · Eron se afasta.')
],'Fale com Eron: ele viu a retirada das coisas de Tomas.');
scene('vestigios','A costura azul','kali','tomasBed',1,[
'A terceira costura esconde um pedaço de papel: “T-17 / revisão antes da saída”. Um fio azul ficou preso no grampo. Tomas costumava remendar a própria coberta com essa linha.',
'O papel tem a mesma borda serrilhada do livro de chamadas. A sala de leitura guarda as cópias antigas. O número T-17 permite procurar uma linha específica, sem revirar todas as páginas.'],[
 C('Guardar o papel e recolocar o colchão.','registro',{flags:{bedClue:true},items:['Etiqueta T-17']},'A etiqueta fica escondida no punho de Kali. O colchão parece intocado. Agora você sabe o que procurar no registro.','Pista: T-17 → livro de chamadas.')
],'Examine a costura do colchão de Tomas no dormitório.');
scene('registro','Uma transferência sem destino','kali','ledger',1,[
'No livro, T-17 corresponde a Tomas. A coluna “destino” está vazia. Alguém escreveu “material entregue à cozinha” por cima de “morador em revisão”. Não é um registro de viagem.',
'Na margem, a bibliotecária copiou uma instrução antiga: “O sino chama. A chama revela. A raiz guarda”. Ao lado, três pequenos desenhos reproduzem os discos da base do altar.',
'Você ainda não sabe onde Tomas está. A caixa da cozinha pode ligar a anotação à pessoa que autorizou a retirada.'],[
 C('Copiar a linha e deixar o livro no lugar.','cruzamento',{flags:{registerClue:true,altarClue:true},items:['Cópia do registro T-17']},'Kali copia a ausência de destino e a ordem dos três símbolos. São observações verificáveis. Não uma prova de que Tomas saiu de OldHood.','Pista: livro → caixa da cozinha. Código do altar anotado no diário.'),
 C('Arrancar a página para levar o original.','cruzamento',{suspicion:1,flags:{registerClue:true,altarClue:true,missingPage:true},items:['Página original T-17']},'A página se solta com um ruído seco. O buraco será visto na próxima conferência. Você guarda um original, mas deixa um sinal da investigação.','Vigilância +1 · a página ausente fica visível.')
],'Procure T-17 no livro da sala de leitura.');
scene('cruzamento','O que a caixa prova','kali','box',1,[
'A caixa atrás da cozinha tem o número T-17. Dentro estão a caneca lascada e a coberta azul. Nenhuma bagagem foi preparada para a estrada.',
'Uma requisição presa na tampa pede “manter na ala leste até a segunda chamada”. A assinatura é da sala de observação. Tomas está sendo retido dentro do orfanato.',
'Mira conhece a distribuição de comida para a ala leste. Eron conhece a ronda da cozinha. Você pode usar relações diferentes para chegar à mesma porta.'],[
 C('Recolher a requisição e levar a descoberta a Mira.','plano',{flags:{kitchenClue:true},items:['Requisição da ala leste']},'Kali deixa a caixa fechada. Antes de sair, nota uma caixa de reparos sobre a bancada: um arame pode ser útil numa fechadura.','Pista confirmada: Tomas continua em OldHood. Mira está no salão.')
],'Examine a caixa numerada atrás da cozinha.');
scene('plano','Ninguém vai desaparecer sem nome','mira','mira',1,[
'— A ala leste recebe duas bandejas a mais — diz Mira, lendo a requisição. — Eles dizem que são para os vigias. Tomas pode estar atrás da segunda porta.',
'— Vamos abrir?\n— E tirar alguém para correr para onde? Primeiro uma entrada. Depois uma saída. Uma promessa sem caminho só prende outra pessoa.',
'Você tem três formas de preparar o acesso. A obediência pode render uma chave; Eron pode preparar uma distração; observar a ronda permite agir sozinho. A bancada da cozinha tem uma ferramenta opcional.'],[
 C('Combinar um caminho com Eron.','bilhete',{flags:{planEron:true}},'— Ele deixa recados na sua cama — diz Mira. — Quando falar de passos, escute os intervalos. Ele só oferece o que consegue cumprir.','Rota de aliados · fortaleça Eron e conheça a passagem.'),
 C('Usar o serviço de bandejas para ganhar acesso.','explorar',{adults:1,flags:{planCover:true}},'Mira entrega uma bandeja vazia. — Não diga que soube por mim. Eles gostam de uma explicação pequena. “Vim ajudar” basta.','Rota de disfarce · confiança dos adultos +1.'),
 C('Estudar a ronda sem envolver outra pessoa.','ronda',{},'— Então marque a volta completa, não apenas a ida — Mira avisa. — Você pode levar o arame da bancada. E ainda pode pedir ajuda depois.','Rota independente · observe a cozinha antes do interrogatório.')
],'Mostre a requisição a Mira no salão e escolha um plano.');
scene('bilhete','O encontro tem um motivo','kali','bed',1,['O bilhete de Eron não pede confiança cega: “A cozinha esconde a escada de serviço. Se quiser tirar Tomas, precisa saber onde ela termina. Venha à bancada depois da ronda.”'],[
 C('Ir ao encontro.','eron',{},'Você memoriza o recado e o esconde na costura. Eron espera no fundo da cozinha.','Objetivo: aprender uma saída antes de abrir as celas.'),
 C('Investigar a ronda sozinho.','ronda',{},'Kali deixa o bilhete onde estava. Ainda é possível observar o vigia da entrada da cozinha.','Você abre mão desta conversa, não da investigação.')
],'Leia o bilhete de Eron na sua cama.');
scene('eron','Um plano que cabe em três batidas','eron','eronKitchen',1,[
'— A escada da cozinha desce aos arquivos. O ramal esquerdo chega ao portão. O direito termina no depósito de carvão. Tem uma porta falsa lá — explica Eron.',
'— E a ala leste?\n— Quando eu derrubar as panelas, o vigia vem até aqui. Você abre a cela. Mas só farei isso depois de combinarmos. Não me deixe esperando um sinal que não vem.',
'Eron risca o percurso na gordura da bancada e deixa Kali repetir as curvas. Conhecer o trajeto não abre a porta: isso ainda exige uma chave, uma ferramenta ou a distração.'],[
 C('Repetir o trajeto e combinar três batidas.','ferramentas',{eron:1,flags:{passage:true,signalKnown:true},items:['Trajeto de Eron']},'— Esquerda para fora. Três batidas para a distração.\nEron apaga o desenho. — Agora o plano existe na cabeça de duas pessoas.','Trajeto aprendido · Eron +1 · distração disponível com confiança 2.'),
 C('Aprender o caminho, sem pedir que ele se arrisque.','ferramentas',{flags:{passage:true},items:['Trajeto de Eron']},'— Certo. Não vou derrubar nada sem você pedir.\nEron aponta a caixa de reparos. — Pegue uma ferramenta. Porta fechada não escuta intenção.','Trajeto aprendido · Eron não estará comprometido com uma distração.')
],'Combine a saída com Eron no fundo da cozinha.');
scene('ferramentas','A ferramenta e o barulho','kali','tools',1,['A caixa de reparos tem um arame rígido e um pano. O arame abre a lingueta das celas; o pano abafa o metal. Uma marca de poeira denuncia se a caixa for deixada aberta.'],[
 C('Levar o arame e fechar a caixa.','ronda',{flags:{toolTaken:true},items:['Arame']},'O arame vai para o bolso. Só será consumido se você o usar na fechadura.','Objeto utilizável: Arame.'),
 C('Deixar a ferramenta.','ronda',{},'Você prefere uma chave ou a ajuda de Eron. Pode voltar à caixa antes do confronto.','A ferramenta continua disponível na bancada.')
],'Examine a caixa de reparos na bancada da cozinha.');
scene('explorar','A bandeja como disfarce','guard','service',1,['— Sobrou trabalho? — Kali pergunta com a bandeja nas mãos.\n— Sempre sobra. Leve uma conta limpa à observação depois que a ronda passar.','O vigia oferece uma braçadeira de serviço. Vestir o símbolo da Actras dá acesso aos adultos, mas Mira verá de que lado você parece estar. Você poderá explicar a ela o plano.'],[
 C('Vestir a braçadeira para conseguir uma chave depois.','ronda',{adults:2,mira:-1,flags:{cover:true},items:['Braçadeira de serviço']},'O vigia passa a chamar Kali pelo nome. Do salão, Mira vê a braçadeira e desvia o olhar.','Adultos +2 · Mira −1 · disfarce visível no personagem.'),
 C('Entregar a bandeja e recusar a braçadeira.','ronda',{adults:1},'— Prefiro só carregar.\nO vigia aceita a ajuda, mas guarda a braçadeira.','Adultos +1 · sem identificação de serviço.')
],'Peça trabalho ao vigia na entrada da cozinha.');
scene('ronda','A volta que ninguém conta','kali','watch',1,[
'Perto da entrada da cozinha, Kali observa uma volta completa. O vigia cruza o corredor, confere as panelas e retorna para fechar a grade da ala leste. A abertura acontece na volta, depois do sino.',
'Isso ensina quando passar, mas não elimina o perigo. Durante a exploração, o campo de visão dos vigias é real. Caminhar com Shift reduz o alcance em que percebem você.',
'Quando a volta termina, o vigia anuncia: — Kali, na sala de observação. Agora. A investigação continua, mas a chamada não pode ser ignorada.'],[
 C('Anotar: esperar o sino, passar na volta.','interrogatorio',{flags:{timing:true},items:['Horário da ronda']},'Você registra o intervalo no diário. A sala de observação fica ao sul da cozinha; a entrada dos arquivos permanece trancada.','Ronda estudada · alternativa de acesso disponível.')
],'Observe o ciclo da ronda na entrada da cozinha.');
scene('interrogatorio','O que eles já sabem','guard','examiner',2,s=>[
 s.flags.disclosed?'O vigia repete uma frase que Kali só disse a Noah. Não comenta de onde a ouviu. “Sua família seguia outra luz. Foi isso que você disse?”':'O vigia põe o registro de chamadas sobre a mesa. “Você anda perguntando por um morador transferido.”',
'— A coluna de destino está vazia — Kali responde.\nO adulto fecha o livro. — Não é você quem preenche essa coluna. Aqui, as perguntas têm consequências para quem responde.',
'Kali vê duas chaves na mesa. Uma tem uma fita branca: a mesma cor da marca na grade da ala leste. O interrogatório também revelou onde conseguir acesso.'],[
 C('“Eu só queria entender a distribuição das bandejas.”','sumico',{adults:1,suspicion:-1,flags:{keySeen:true}},'O vigia devolve a bandeja. — Seja útil e não terá problemas.\nAo voltar, Kali encontra a cama de Mira vazia.','Adultos +1 · vigilância −1 · localização da chave anotada.'),
 C('“Não vou dar o nome de quem falou comigo.”','sumico',{mira:1,eron:1,suspicion:1,flags:{keySeen:true}},'O adulto espera. Kali não acrescenta um nome. — Pode ir. Por enquanto.\nNo dormitório, a cama de Mira foi esvaziada.','Mira e Eron +1 · vigilância +1.'),
 C('“Minha crença não é um crime. E Tomas não saiu daqui.”','sumico',{suspicion:2,mira:1,flags:{faith:true,keySeen:true}},'— Repita isso diante de todos e veremos.\nKali sai com a certeza de que a Actras está escondendo Tomas. A cama de Mira agora também está vazia.','Vigilância +2 · Mira +1 · a patrulha passa a observar mais longe.'),
 C('Entregar o nome de Eron para encerrar a investigação contra você.','sumico',{adults:2,suspicion:-2,mira:-2,flags:{eronBetrayed:true,keySeen:true}},'— Foi Eron. Ele levantou a tábua.\nO vigia anota o nome. Eron é levado para a ala leste; quando passa por Kali, não pede uma explicação. A promessa que você fez já foi respondida.','IRREVERSÍVEL: Eron preso; sem sua ajuda, distração ou fuga coletiva.')
],'Atenda à chamada na sala de observação e observe a mesa.');
scene('sumico','A segunda cama vazia','kali','miraBed',2,[
'A cama de Mira ainda está quente. Debaixo da caneca, ela deixou um recado: “Me levaram para a primeira cela. Tomas está atrás da divisória. Não aceite a porta aberta que Noah oferecer.”',
'No verso: “Ele descreveu meu encontro com você antes de o vigia me chamar. Se ele quiser ajudar, peça que abra o trinco do portão. Uma ação. Não outra promessa.”',
'O recado não é uma sentença contra Noah. É uma forma de verificar o que ele fizer daqui em diante. Mira deu uma localização e um teste concreto.'],[
 C('Guardar o recado e procurar Noah.','oferta',{flags:{warning:true,miraTaken:true},items:['Aviso de Mira']},'Noah espera ao lado do armário. A cela de Mira é agora um destino conhecido; antes de ir, você precisa decidir o que fazer com a oferta dele.','Mira está na ala restrita · o diário agora inclui seu resgate.')
],'Procure o recado deixado na cama de Mira.');
scene('oferta','A ajuda que dispensa perguntas','noah','noahDorm',2,[
'— Sei onde está seu símbolo — Noah diz. — A sala de observação vai ficar aberta. Dá tempo de pegar antes de olharem.',
'— E Mira?\n— Não posso resolver tudo. Seu símbolo é o que importa para você, não é?',
'O aviso de Mira pesa no bolso. A história de Noah aponta para uma sala onde você acabou de ver um vigia. Seu objeto foi catalogado; os arquivos ficam em outro lugar.'],[
 C('Exigir uma explicação sobre o recado de Mira.','questionar',{},'— Como você sabia do encontro antes da chamada?\nPela primeira vez, Noah não responde depressa.','Confrontar abre a chance de exigir uma reparação.'),
 C('Verificar a porta antes de entrar.','limiar',{},'— Vá na frente. Eu olho o corredor.\nNoah concorda, mas não se afasta o suficiente para perder Kali de vista.','Cautela · você terá uma última chance de recuar.'),
 C('Seguir Noah sem verificar.','emboscada',{noah:1},'Noah caminha depressa. Na sala, uma cadeira já foi colocada diante da câmera.','PERIGO: você ignora uma contradição e o aviso de Mira.'),
 C('Recusar e procurar um acesso à ala leste.','confinamento',{},'— Não vou trocar uma pessoa por um objeto.\nKali deixa Noah no dormitório. O sino do confinamento começa a tocar.','Você encerra a oferta; a verdade sobre Noah continuará incompleta.')
],'Ouça a oferta de Noah e confronte o aviso de Mira.');
scene('limiar','Dois pares de passos','kali','officeDoor',2,['A luz sai por baixo da porta. Kali ouve o arrastar do vigia e uma segunda voz: “Ele vem sozinho?” Noah faz sinal para entrar. Não há objeto sobre a mesa.'],[
 C('Recuar e enfrentar Noah no dormitório.','questionar',{flags:{trapSeen:true}},'— Você disse que estaria vazia.\nNoah acompanha Kali de volta. Já não consegue repetir a primeira versão.','A armadilha foi verificada.'),
 C('Entrar mesmo assim.','emboscada',{},'A porta fecha atrás de Kali antes que ele termine a primeira pergunta.','IRREVERSÍVEL: dois adultos esperam dentro da sala.')
],'Escute do lado de fora da sala de observação.');
scene('emboscada','Uma cadeira preparada','noah','examiner',2,['— Disseram que você só precisava falar — Noah murmura.\n— Você viu a cadeira. Você sabia.\nNoah aperta a manga entre os dedos. Não responde.','O vigia toma o recado antes de Kali alcançar o bolso. A câmera já estava gravando. A escolha de entrar entregou à Actras a investigação e quem a conduzia.'],[
 C('Encarar Noah enquanto a porta é trancada.','traicao',{flags:{betrayed:true}},'Noah baixa os olhos. Nenhuma das respostas que decorou serve para o que acabou de fazer.','Este caminho termina aqui.')
],'Entre na sala onde Noah o levou.');
scene('questionar','As palavras que ele entregou','noah','noahDorm',2,[
'Kali mostra o aviso. — Mira não sumiu por desobedecer a uma regra. Sumiu depois que você contou o que ouviu.',
'— Eles já tinham suspeitas. Disseram que, se eu ajudasse, parariam de perguntar sobre mim.\n— E passaram a perguntar sobre ela.\nNoah olha para a porta. — Eu sei.',
'Ele não pede perdão. Pergunta o que Kali pretende fazer. Pela primeira vez, a conversa pode exigir um gesto verificável.'],[
 C('“Conte como as portas funcionam. Depois decida quem vai ajudar.”','verdade',{flags:{confronted:true}},'Noah explica que o portão tem um trinco interno. Alguém pode soltá-lo sem uma chave, mas ficará exposto ao vigia do corredor.','A ajuda de Noah precisará de uma ação real.'),
 C('“Não vou entregar outra pessoa para proteger você.”','confinamento',{flags:{confronted:true,rejected:true}},'— Não estou pedindo um nome — Noah responde.\n— Foi assim que começou com Mira.\nKali sai para procurar a grade da ala leste.','Noah foi confrontado; você recusou formar um acordo.')
],'Peça a Noah que explique por que Mira foi levada.');
scene('verdade','Uma reparação não é um perdão','noah','noahDorm',2,[
'— Se eu abrir, vão saber que fui eu — Noah diz.\n— Se não abrir, vamos saber também.\nKali guarda o recado. — Não quero que prometa ser outra pessoa. Quero que solte o trinco do portão.',
'Noah passa o polegar pela marca da chave na palma. — Vou esperar no fim do corredor. Fale comigo lá, antes de levar os outros.\nA palavra dele ainda não é uma saída.'],[
 C('Dar a Noah a tarefa de abrir o trinco.','confinamento',{noah:1,flags:{mercy:true,noahDoubt:true,noahTask:true}},'— Eu vou conferir — Kali avisa.\n— Eu sei.\nNoah deixa o dormitório. O mapa agora marca o trinco como preparação opcional.','Nova tarefa: verificar Noah no portão. Perdão não foi concedido.'),
 C('Recusar depender dele.','confinamento',{flags:{rejected:true}},'Kali decide que a saída precisa depender de uma chave ou dos aliados que já ajudaram. Noah permanece no dormitório.','Outras rotas continuam abertas.')
],'Decida se Noah terá a chance de reparar uma parte do que fez.');
scene('confinamento','Primeiro, abrir a grade','guard','guardHall',3,s=>[
'O sino muda de ritmo. — Todos nos quartos. Só o serviço de bandejas passa — ordena o vigia. A grade da ala leste se fecha diante de Kali.',
'Você sabe que Mira está na primeira cela e Tomas atrás da divisória. Pode pedir a chave, distrair o vigia com Eron, usar um arame ou aproveitar a próxima abertura da ronda.',
'Os requisitos e o risco de cada método estão abaixo. Antes de escolher, ainda é possível pegar a ferramenta da cozinha, falar com aliados ou abrir o diário.'],[
 C('Pedir a chave usando a confiança dos adultos.','chave',{flags:{authorized:true}},'— A de fita branca está na mesa. Devolva quando terminar — diz o vigia. A obediência comprou acesso, não liberdade.','Acesso discreto · vá buscar a chave na sala de observação.',s=>s.adults>=3?null:'Precisa de confiança 3 com os adultos. Serviço de bandejas ajuda.'),
 C('Pedir que Eron provoque a distração combinada.','distracao',{},'Kali procura a cozinha. Eron só fará o barulho quando ouvir o sinal; ninguém precisa arriscar uma corrida antes da hora.','Uma distração afasta parte da patrulha.',s=>!s.flags.eronBetrayed&&s.eron>=2?null:'Precisa de Eron livre e confiança 2. Converse com ele ou entregue um plano.'),
 C('Ir até a fechadura e usar ferramenta ou intervalo.','fechadura',{},'Kali vai até a grade, ao norte do corredor. O sino marca o retorno da ronda.','Arame: +1 vigilância. Intervalo estudado: +2. O risco é mostrado antes de agir.'),
 C('Deixar o resgate para trás e procurar os arquivos.','subsolo',{flags:{rescueSkipped:true}},'Kali segue para o altar. Os registros podem confirmar o paradeiro de Tomas, mas Mira continua atrás da grade. A porta poderá ser reaberta antes da fuga.','Mira permanece presa; ainda é possível voltar antes do confronto.')
],'Escolha como acessar a ala restrita durante o confinamento.');
scene('chave','A fita branca','kali','keyDesk',3,['A chave está onde o vigia indicou. A fita branca abre a grade e as celas. Devolvê-la agora preservaria o disfarce, mas deixaria Mira trancada. Kali precisa usá-la primeiro.'],[
 C('Pegar a chave e ir até a grade da ala leste.','fechadura',{flags:{key:true},items:['Chave da ala leste']},'A chave está com você. Vá até a grade, ao norte do corredor, e use-a na fechadura.','Chave obtida · ainda é preciso abrir a grade.')
],'Pegue a chave de fita branca na mesa da sala de observação.');
scene('distracao','Três batidas na bancada','eron','eronKitchen',3,['— Você vai mesmo abrir? — Eron pergunta.\n— Vou. Quando ouvir as panelas, vou para a grade.\n— Então conte as três. Não corra antes.','Eron coloca uma pilha instável perto da passagem. O barulho vai prender o vigia à cozinha pelo restante desta preparação. A patrulha do corredor continua.'],[
 C('Dar três batidas e confirmar o resgate.','resgate',{eron:1,flags:{organized:true,distracted:true,cell:true,cellOpen:true}},'As panelas caem. O vigia da cozinha e o do salão vão ajudar. A grade fica destrancada; Mira ouve o barulho do outro lado.','Dois vigias deixam de patrulhar · grade aberta · Eron +1.')
],'Dê o sinal a Eron no fundo da cozinha.');
scene('fechadura','A lingueta por dentro','kali','cellDoor',3,s=>[
'A grade deixa ver a lingueta. Um arame pode levantá-la. Sem ferramenta, você pode esperar o vigia abrir depois do sino e impedir que a porta feche.',
 s.suspicion>=5?'A vigilância já está crítica. Forçar esta porta agora pode provocar uma captura. Ainda pode voltar para buscar uma chave ou preparar Eron.':'Ambos os métodos deixam um sinal. O arame faz pouco barulho; travar a porta durante a ronda chama mais atenção.',
'Se ainda não observou a ronda, a entrada da cozinha permite estudá-la. O diário e o mapa mostram esse ponto.'],[
 C('Usar a chave de fita branca.','resgate',{flags:{cell:true,cellOpen:true}},'O mecanismo cede sem ruído. A grade permanece aberta enquanto você entra para falar com Mira.','Grade aberta · sem aumento da vigilância.',s=>s.flags.key?null:'Consiga a chave com autorização dos adultos.'),
 C('Usar o arame para levantar a lingueta.','resgate',{suspicion:1,consume:['Arame'],flags:{cell:true,cellOpen:true,wireUsed:true}},'O arame se entorta e fica preso no mecanismo. Kali abre a grade. O metal solto denuncia uma interferência; a ferramenta não pode ser reutilizada.','Arame consumido · vigilância +1.',s=>item(s,'Arame')?null:'Pegue o arame na bancada da cozinha.'),
 C('Passar depois do sino e bloquear a grade.','resgate',{suspicion:2,flags:{cell:true,cellOpen:true,forcedCell:true}},'Na volta, o vigia abre a grade. Kali prende uma lasca de madeira na lingueta e espera os passos sumirem. A porta não fecha como deveria.','Vigilância +2 · a grade avariada ficará visível.',s=>s.flags.timing?null:'Estude a ronda na entrada da cozinha primeiro.'),
 C('Voltar e escolher outro método.','confinamento',{},'Kali deixa a grade intocada. Uma ferramenta, um aliado ou o serviço de bandejas ainda podem mudar a situação.','Você pode preparar outra forma de entrar.')
],'Examine a fechadura na entrada da ala restrita.');
scene('resgate','Uma promessa precisa de uma porta','mira','miraCell',3,[
'Mira se aproxima da grade. — Ouvi Tomas atrás da divisória. Não o deixaram falar desde ontem. A ordem diz que vão nos levar ao amanhecer.',
'— Posso abrir a sua agora.\n— Então abra. Não diga que vai voltar só para eu parar de pedir.',
'Ela mostra uma marca no punho. — Os objetos confiscados ficam sob o altar. Há três discos. O livro da sala de leitura guarda a ordem. Nos arquivos, procure o registro de saída: ele prova que ninguém foi transferido ainda.'],[
 C('Libertar Mira e levá-la à cozinha para esperar.','subsolo',{mira:1,flags:{rescued:true,miraTaken:true,passage:true,altarClue:true}},'Kali abre a porta e acompanha Mira até a passagem. Ela seguirá até a cozinha, onde poderá preparar a saída. Uma cela vazia fica para trás.','Mira livre e visível na cozinha · resgate de Tomas agora pode ser preparado.'),
 C('Pedir que espere e ir atrás do registro primeiro.','subsolo',{mira:-1,flags:{rescueSkipped:true,altarClue:true}},'— Não vou chamar isso de resgate — Mira diz. — Vá buscar a prova. Mas a porta continua entre nós.\nKali guarda a localização dos registros.','Mira −1 · ela permanece na cela. Você pode voltar antes do confronto.')
],'Entre na ala leste e decida se vai libertar Mira agora.');
scene('subsolo','Sino, chama e raiz','kali','altar',3,s=>[
'Três discos cercam a base do obelisco. Um sino, uma chama e uma raiz. O mecanismo é uma porta de manutenção, escondida dentro do ritual da Actras.',
 s.flags.altarClue?'Sua anotação diz: “O sino chama. A chama revela. A raiz guarda.” Pressione os símbolos nessa ordem.':'Uma inscrição pode ser lida sob a toalha: “O sino chama. A chama revela. A raiz guarda.” É uma ordem de abertura.',
'Uma sequência errada faz o sino interno soar e aumenta a vigilância. A inscrição continua disponível; você não precisa adivinhar sem uma pista.'],[
 C('Pressionar sino → chama → raiz.','arquivo',{flags:{tunnel:true,altarClue:true}},'A base desliza. Kali desce a escada e chega aos arquivos. A entrada de manutenção da cozinha também destranca: agora existe um caminho de volta pelo mapa.','Passagem aberta · arquivos acessíveis.'),
 C('Pressionar chama → raiz → sino.','subsolo',{suspicion:1},'O sino interno toca uma vez. A base não se move. A frase começa pelo sino; Kali pode tentar de novo ou se preparar antes.','Erro: vigilância +1. Releia a inscrição.'),
 C('Ler a inscrição sob a toalha.','subsolo',{flags:{altarClue:true}},'“O SINO chama. A CHAMA revela. A RAIZ guarda.” Três verbos, três símbolos, uma ordem. Kali registra a sequência no diário.','Código registrado: sino → chama → raiz.')
],'Resolva o mecanismo de três símbolos na base do altar.');
scene('arquivo','O registro que ainda não aconteceu','kali','records',4,[
'T-17. Tomas. “Ala leste, cela interna. Saída prevista: amanhecer.” A assinatura já está no campo “recebido”, mas o transporte ainda não chegou. A Actras registrou uma transferência que não ocorreu.',
'O documento de Mira foi preparado da mesma maneira. A lista inclui o destino: uma unidade isolada mantida pela própria Actras. Os desaparecimentos formam um procedimento, não acidentes.',
'Kali pode levar prova para quem está fora ou destruir a ordem para atrasar a transferência. O armário ao lado guarda seu símbolo. Depois, será preciso preparar a saída e decidir por quem voltar.'],[
 C('Levar o registro assinado como prova.','reliquia',{flags:{proof:true},items:['Registro de transferência']},'Kali dobra o papel pelas marcas antigas. Agora há nomes, datas, destino e assinatura. A prova poderá ser mostrada aos moradores e entregue fora de OldHood.','Prova obtida · habilita mobilização e muda o epílogo.'),
 C('Destruir a ordem para atrasar o transporte.','reliquia',{flags:{transferDelayed:true}},'Kali rasga a ordem e espalha as partes sob a estante. A saída terá de ser autorizada de novo. Isso ganha tempo para Tomas, mas elimina a prova assinada.','Transporte atrasado · a prova original foi perdida.')
],'Leia o registro T-17 nos arquivos subterrâneos.');
scene('reliquia','A lembrança e as pessoas','kali','relic',4,[
'O símbolo está num envelope marcado com a data do acidente. O cordão ainda tem barro no nó. Kali o reconhece antes de tocar.',
'Não há uma explicação sobre a morte de seus pais no envelope. Só a ordem de entrada em OldHood e a classificação “objeto não permitido”. Kali não transforma essa ausência numa resposta.',
'Recuperar a lembrança era um começo. O destino de Tomas depende do que você fez antes do último sino. Uma saída sem plano pode terminar na primeira curva. Eron espera na cozinha; você pode preparar ajuda antes de enfrentar a saída.'],[
 C('Guardar o símbolo e reunir o que falta para fugir.','preparar',{flags:{relic:true},items:['Símbolo do Luzitruismo']},'O metal volta à palma de Kali. Cada preparação custa uma ação do prazo de Tomas. Caminhar e ler não gastam ações. O diário mostra o que falta para cada rota.','Preparação sob prazo: priorize pessoas, aliados e saída. Confira as ações restantes.')
],'Recupere o símbolo no armário dos arquivos.');
const groupReady=s=>!s.flags.eronBetrayed&&s.flags.rescued&&s.eron>=2&&s.flags.escapePlan&&(s.mira>=2||s.flags.proof);
const noahReady=s=>!s.flags.eronBetrayed&&s.flags.latchOpen&&s.flags.rescued&&s.eron>=2;
scene('preparar','Antes que o sino toque outra vez','kali','meeting',4,s=>[
s.flags.eronBetrayed?'O lugar de Eron na cozinha está vazio. Kali escreveu o nome dele para escapar da própria acusação. Agora terá de escolher um caminho sem sua ajuda.':'— Quem vai sair? — Eron pergunta.\nKali precisa responder com nomes e tarefas. Mira pode orientar os moradores. Eron precisa de um trajeto. Tomas não abrirá a cela por dentro. Noah precisa cumprir o que prometeu.',
'Você pode voltar aos cômodos, usar os objetos e preparar aliados. O mapa marca os pontos opcionais em azul. O diário explica o que cada rota exige.',
'Confirmar abaixo inicia o confronto. Até esse momento, você pode mudar de ideia e completar o que estiver faltando. Depois, a Actras fechará o cerco.'],[
 C('Revisar as tarefas e continuar explorando.','preparar',{},s=>plan(s).map(p=>(p.done?'✓ ':'○ ')+p.text).join('\n'),'Preparações abertas. Use E nos personagens e objetos marcados.'),
 C('Estou pronto: seguir para a saída.','confronto',{flags:{committed:true}},s=>'O líder intercepta Kali no corredor. Eron se afasta da passagem para não entregar o plano.\n'+(groupReady(s)?'Seu grupo tem resgate, confiança e um trajeto combinado.':noahReady(s)?'Noah soltou o trinco; Mira e Eron podem alcançar a porta.':'Confira as condições antes de escolher uma fuga. As opções mostram os riscos.'),'IRREVERSÍVEL: encerra a preparação livre. Confira o diário antes.')
],'Prepare a fuga e confirme o plano na mesa da cozinha.');
scene('confronto','O que sua escolha pode cumprir','leader','climax',4,s=>[
'— Você confundiu cuidado com permissão — o líder diz, bloqueando o corredor.\n— Vocês assinaram saídas de pessoas que ainda estavam presas — Kali responde.',
 s.flags.proof?'Kali ergue o registro. Pela primeira vez, os moradores veem uma assinatura onde antes só ouviam ordens.':'A ordem não está com Kali. A acusação precisa ser sustentada por quem conseguiu libertar e pelo que os outros viram.',
'Os caminhos abaixo mostram o que você preparou e o que falta. Escolher uma rota incompleta tem um risco concreto; confiança, pessoas livres e portas abertas não são intercambiáveis.'],s=>[
 C(groupReady(s)?'Dar o sinal combinado e sair com o grupo.':'Chamar o grupo mesmo sem preparação suficiente.',groupReady(s)?'travessia':'captura',{flags:{escapeGroup:true}},groupReady(s)?'Mira organiza a fila; Eron aponta a curva. Atravesse o corredor até a última porta. Ainda é preciso chegar lá.':'O sinal não encontra um grupo preparado. Os vigias isolam Kali antes que alguém consiga abrir a passagem.',groupReady(s)?'ROTA PREPARADA: Mira livre, apoio e trajeto combinado.':groupReason(s)+' Esta tentativa termina em captura.'),
 C('Usar a confiança dos adultos como disfarce.','disfarce',{},'— Posso levar os outros de volta — Kali diz. O líder reconhece o serviço que ele prestou e permite a passagem.','Você poderá fugir ou usar o acesso para voltar.',s=>s.flags.coverBurned?'A braçadeira foi confiscada; o disfarce acabou.':s.adults>=3?null:'Exige confiança 3 com os adultos.'),
 C(noahReady(s)?'Usar o trinco que Noah abriu.':'Depender de Noah sem uma saída verificada.',noahReady(s)?'travessia':'traicao',{flags:{escapeNoah:true}},noahReady(s)?'Noah ergue a mão. O trinco está solto. Mira e Eron seguem para a porta lateral. Kali ainda precisa atravessar o corredor.':'Noah não preparou uma saída para o grupo. Diante do líder, entrega o símbolo que Kali estende. A promessa sem ação não abriu a porta.',noahReady(s)?'ROTA VERIFICADA: trinco aberto, Mira livre e Eron aliado.':'Falta '+(!s.flags.latchOpen?'verificar o trinco com Noah':!s.flags.rescued?'libertar Mira':'preparar Eron')+'. Confiar nesta rota termina em traição.'),
 C('Correr sozinho pela passagem de serviço.',s.flags.passage?'travessia':'isolamento',{flags:{escapeSolo:true}},s.flags.passage?'Kali conhece a curva. Segue sozinho para o portão, deixando os outros sem o sinal.':'Sem conhecer o trajeto, Kali entra no ramal de carvão. A parede ao fundo não é uma porta.',s.flags.passage?'Você conhece a saída, mas abandonará o grupo.':'Você não aprendeu o trajeto. A tentativa termina em isolamento.')
],'Enfrente o líder no corredor e escolha uma rota preparada.');
scene('travessia','A última curva','kali','escapeTurn',4,s=>[
 s.flags.escapeSolo?'Kali segue sozinho. O corredor parece maior sem alguém para confirmar a direção.':'Mira e Eron alcançam a última curva. O vigia ainda patrulha o corredor. Quando ele se virar, Kali pode avançar furtivamente até o portão.',
'Chegar até aqui exigiu decisões. Sair ainda exige atravessar o lugar que elas mudaram. O portão fica no extremo leste do corredor.'],[
 C('Conferir a curva e avançar até o portão.','portao',{},'A porta está ao fim do corredor. O som do sino fica atrás de Kali.','Último objetivo: alcançar o portão sem ser capturado.')
],'Atravesse o corredor até a última curva, evitando o vigia.');
scene('portao','Do lado de fora','kali','exit',4,['A madeira cede. O ar da madrugada entra pela fresta. Kali segura o símbolo, mas olha primeiro para quem conseguiu chegar até ali.'],[
 C('Atravessar o portão.',s=>s.flags.escapeSolo?'sobrevivente':s.flags.escapeNoah?'luz':'voz',{},'','O epílogo registra quem saiu, quem ficou e o destino das provas.')
],'Chegue ao portão e atravesse para concluir a fuga.');
scene('disfarce','A liberdade de quem?','kali','exit',4,[
'O líder permitiu que Kali circulasse para recolher os moradores. A mesma autorização pode levar uma pessoa para fora ou abrir caminho para várias.',
'Voltar exige a chave ou uma distração organizada e Mira livre. Sem acesso, os vigias retornarão antes que a primeira porta ceda.'],s=>[
 C('Aproveitar a autorização e fugir sozinho.','sobrevivente',{flags:{escapeSolo:true}},'Kali atravessa antes que o vigia confira a lista.','Você sai; os demais não recebem seu sinal.'),
 C('Voltar para abrir as portas e levar os outros.',!s.flags.eronBetrayed&&(s.flags.key||s.flags.organized&&s.flags.rescued)?'voz':'captura',{flags:{returned:true}},s.flags.eronBetrayed?'A chave alcança a grade, mas o nome que Kali entregou não pode reunir ninguém. Sem Eron, a tentativa de retorno termina sob o cerco.':s.flags.key?'A chave abre as celas de Mira e Tomas. Eron desperta os outros. Kali usa a última ordem do líder para conduzir todos para fora.':s.flags.organized&&s.flags.rescued?'Eron sustenta a distração. Mira reúne os moradores. Kali volta pelo corredor que acabou de liberar.':'Sem chave nem aliados preparados, Kali demora na primeira grade. Os vigias retomam o corredor.',s.flags.eronBetrayed?'PERIGO: Eron foi denunciado. O retorno coletivo termina em captura.':s.flags.key?'Chave disponível: abre as celas de quem ainda estiver aqui.':s.flags.organized&&s.flags.rescued?'Distração e Mira livre: retorno preparado.':'PERIGO: faltam acesso e apoio. Voltar assim termina em captura.')
],'Use seu disfarce no portão: fugir ou voltar pelos outros.');
['ferramentas','ronda','fechadura','chave','distracao','arquivo','reliquia','preparar','travessia','portao'].forEach(s=>M.night.add(s));
const flagMessages={bedClue:'Etiqueta encontrada: Tomas → T-17.',registerClue:'O registro não possui destino. A caixa da cozinha é a próxima pista.',kitchenClue:'Confirmado: Tomas foi retido na ala leste.',cover:'Kali veste a braçadeira de serviço.',protectedEron:'Eron lembra que você o protegeu.',warning:'O recado de Mira revelou a contradição de Noah.',cellOpen:'A grade da ala leste está aberta.',distracted:'Os vigias da cozinha e do salão foram atraídos pelas panelas.',rescued:'A cela de Mira ficou vazia. Ela espera na cozinha.',tomasRescued:'Tomas deixou a cela interna e aguarda junto de Mira.',tunnel:'A passagem do altar e a porta dos arquivos foram abertas.',proof:'O registro assinado está com você.',transferDelayed:'A ordem foi destruída. A transferência foi atrasada.',escapePlan:'Eron combinou a saída pela esquerda com os moradores.',latchOpen:'Noah abriu o trinco; a ajuda dele agora pode ser verificada.',fedMira:'Mira recebeu sua parte do pão.',coverExplained:'Mira sabe que a braçadeira é um disfarce.',cameraCovered:'A câmera do dormitório está coberta.',missingPage:'Uma página arrancada denuncia a busca na sala de leitura.'};
const stats={mira:'Mira',eron:'Eron',noah:'Noah',adults:'Adultos',suspicion:'Vigilância'};
function normalize(s){if(s.revision!==3){if(['resgate','subsolo','confronto','disfarce'].includes(s.scene)&&s.flags.cell)s.flags.cellOpen=true;if(['sumico','oferta','questionar','verdade','confinamento','resgate','subsolo','confronto','disfarce'].includes(s.scene))s.flags.miraTaken=true;if(['confronto','disfarce'].includes(s.scene))s.flags.tunnel=true;}s.revision=3;s.events=Array.isArray(s.events)?s.events:[];return s;}
function changes(old,s,e={}){normalize(s);const changes=[];for(const [k,label]of Object.entries(stats)){const d=s[k]-old[k];if(d)changes.push(label+' '+(d>0?'+':'')+d);}for(const [k,msg]of Object.entries(flagMessages))if(s.flags[k]&&!old.flags[k])changes.push(msg);for(const i of s.inventory)if(!old.inventory.includes(i))changes.push('Obtido: '+i+'.');for(const i of old.inventory)if(!s.inventory.includes(i))changes.push('Usado: '+i+'.');if(changes.length)s.events.push({title:G.scenes[old.scene]?.title||'Exploração',changes});s.events=s.events.slice(-80);return changes;}
const originalTake=G.take;
G.take=(state,index)=>{const choice=G.choices(state)[index];const effect=G.value(choice?.effect,state)||{};const next=originalTake(state,index);if(effect.consume)next.inventory=next.inventory.filter(i=>!effect.consume.includes(i));if(next.scene==='sumico')next.flags.miraTaken=true;if(state.scene==='fechadura'&&next.scene==='resgate'&&next.suspicion>=7&&(effect.suspicion||0)>0){next.scene='captura';next.pending={text:'O metal ressoa num corredor sob vigilância crítica. O vigia chega antes que Kali consiga atravessar a grade.',note:'A soma da vigilância e do método escolhido atingiu 7.'};}if(next.flags.returned&&next.scene==='voz'&&next.flags.key){next.flags.rescued=true;next.flags.tomasRescued=true;}const diff=changes(state,next,effect);if(next.pending)next.pending.changes=diff;return next;};
// Reações e interações opcionais são únicas: não permitem acumular confiança repetindo cliques.
const actions={
 bread:{target:'bread',name:'Cesto de pão',act:1,done:'breadTaken',title:'Uma porção guardada',who:'kali',text:'Há um pedaço de pão embrulhado para o serviço da noite. Você pode levá-lo para Mira. Não abre uma porta, mas mostra que a sua promessa inclui o que acontece antes da fuga.',choices:[{label:'Guardar o pão para Mira.',effect:{flags:{breadTaken:true},items:['Pão']},response:'O pão vai para o bolso. Ao falar com Mira, você poderá entregá-lo.'}]},
 tools:{target:'tools',name:'Caixa de reparos',act:1,done:'toolTaken',title:'A lingueta e o arame',who:'kali',text:'O arame rígido abre a grade da ala leste. Será consumido ao usar. A ferramenta não abre o portão final.',choices:[{label:'Pegar o arame.',effect:{flags:{toolTaken:true},items:['Arame']},response:'Você fecha a caixa e guarda o arame. A opção aparecerá diante da grade.'}]},
 studyRoute:{target:'watch',name:'Observar a ronda',act:1,done:'timing',title:'Esperar a volta',who:'kali',text:'Kali observa o caminho inteiro. A grade abre quando o vigia retorna depois do sino, não quando ele parte.',choices:[{label:'Anotar o intervalo.',effect:{flags:{timing:true},items:['Horário da ronda']},response:'Intervalo registrado. Você pode usar a passagem do vigia como alternativa ao arame.'}]},
 camera:{target:'cover',name:'Câmera do dormitório',act:1,done:'cameraCovered',title:'Um lençol no lugar certo',who:'kali',text:'Um lençol pendurado no armário pode cobrir a câmera. Isso apaga parte do rastro no dormitório, mas não impede os vigias de verem você nos corredores.',choices:[{label:'Estender o lençol diante da lente.',effect:{suspicion:-1,flags:{cameraCovered:true}},response:'A luz vermelha desaparece atrás do tecido. A vigilância cai um ponto; as rondas continuam.'}]},
 mira:{target:'mira',name:'Conversar com Mira',act:1,title:'O que você consegue cumprir?',who:'mira',text:s=>s.flags.rescued?'— Estou fora da cela. Ainda não estou fora daqui — Mira lembra. — Diga a Eron quem vai sair e não deixe Tomas na divisória.':s.flags.miraTaken?'Mira segura a grade. — Estou aqui. Não numa lista de transferências. Se quiser ajudar, comece pela fechadura.':'— Não preciso que você concorde com tudo — diz Mira. — Preciso saber o que vai fazer quando o vigia perguntar meu nome.',choices:[
 {label:'Entregar sua porção de pão.',once:'fedMira',requires:s=>!item(s,'Pão')?'Pegue o pão na bancada da cozinha.':null,effect:{mira:1,consume:['Pão'],flags:{fedMira:true}},response:'Mira parte o pão e guarda metade para Tomas. — Vou lembrar disso. Agora precisamos da porta.'},
 {label:'Explicar por que vestiu a braçadeira.',once:'coverExplained',requires:s=>s.flags.cover?null:'Você não veste a braçadeira de serviço.',effect:{mira:1,flags:{coverExplained:true}},response:'Kali explica a chave de fita branca. — Não estou trabalhando para eles. Estou usando o trabalho para chegar à grade.\n— Então me mostre quando abrir — Mira responde.'},
 {label:'Usar a grade aberta para libertá-la.',once:'rescued',requires:s=>!s.flags.miraTaken?'Mira ainda está livre.':!s.flags.rescueSkipped&&s.scene!=='preparar'?'Conclua a conversa principal do resgate primeiro.':!s.flags.cellOpen?'Abra a grade da ala leste primeiro.':null,effect:{mira:1,flags:{rescued:true,passage:true,altarClue:true}},response:'Kali abre a cela. Mira segue para a cozinha e espera ao lado da passagem. Você cumpriu a promessa antes de confirmar a fuga.'}
 ]},
 eron:{target:'eronKitchen',name:'Preparar Eron',act:1,title:'Quem faz o quê','who':'eron',text:s=>s.eron>=2?'— Confio em você, mas preciso de uma tarefa — diz Eron. — Mostre o percurso e diga quem vai estar no portão.':'— Você quer que eu arrisque a minha saída pela sua — Eron diz. — Me dê uma razão concreta. Uma prova é melhor do que “confia em mim”.',choices:[
 {label:'Mostrar a requisição da ala leste.',once:'evidenceShared',requires:s=>s.flags.kitchenClue?null:'Encontre a requisição na caixa da cozinha.',effect:{eron:1,flags:{evidenceShared:true}},response:'Eron lê o número de Tomas. — Então ainda dá tempo. Eu ajudo a contar a ronda.'},
 {label:'Aprender o trajeto e assumir uma tarefa na fuga.',once:'pledgedEron',effect:{eron:1,flags:{pledgedEron:true,passage:true},items:['Trajeto de Eron']},response:'— Você abre a porta; eu conto quem passa. Esquerda depois da escada — Eron explica. Kali repete até não trocar a curva.'},
 {label:'Combinar a rota com todos que puderem sair.',once:'escapePlan',requires:s=>!s.flags.relic?'Primeiro descubra o que os arquivos escondem.':s.eron<2?'Eron precisa de confiança 2. Mostre uma prova e assuma uma tarefa.':null,effect:{flags:{escapePlan:true,passage:true}},response:'Eron distribui as tarefas: Mira acompanha a fila, Kali abre a passagem, ele confere os nomes. A rota coletiva agora tem um plano.'}
 ]},
 noah:{target:'exitLatch',name:'Verificar Noah e o trinco',act:3,title:'Faça, depois fale','who':'noah',text:s=>s.flags.noahTask?'— Você pediu uma ação — Noah diz. Ele põe a mão no trinco. — Olhe. Não vire as costas antes de ver.':'Noah não tem uma tarefa combinada com Kali. Abrir esta conversa não apaga o que aconteceu com Mira.',choices:[
 {label:'Observar Noah soltar o trinco.',once:'latchOpen',requires:s=>s.flags.noahTask?null:'Confronte Noah e peça uma reparação concreta primeiro.',effect:{noah:1,flags:{latchOpen:true}},response:'O ferro desce. Kali testa a porta e sente a folga. — Isso não muda o que você fez.\n— Eu sei. Mas muda se ela abre.\nA saída de Noah pode agora ser verificada.'}
 ]},
 tomas:{target:'tomas',name:'Libertar Tomas',act:3,done:'tomasRescued',title:'O nome por trás da divisória',who:'kali',text:'— Tomas?\nA resposta vem baixa. — Eles disseram que eu já tinha ido embora.\nA lingueta da divisória pode ser levantada pelo lado de fora, agora que a grade principal está aberta.',choices:[{label:'Abrir a divisória e levá-lo até Mira.',requires:s=>s.flags.cellOpen?null:'Abra a grade principal primeiro.',effect:{mira:1,flags:{tomasRescued:true}},response:'Tomas sai segurando a caneca. Kali o leva até a passagem da cozinha. Pela primeira vez, o nome T-17 voltou a ser uma pessoa visível.'}]},
 gate:{target:'cellDoor',name:'Grade da ala leste',act:3,done:'cellOpen',title:'Ainda é possível voltar',who:'kali',text:'Você deixou o resgate para depois. Antes do confronto, ainda pode reabrir a grade. Uma chave abre em silêncio; o arame será consumido; usar a ronda aumenta a vigilância.',choices:[
 {label:'Usar a chave de fita branca.',requires:s=>s.flags.key?null:'Você não tem a chave.',effect:{flags:{cellOpen:true}},response:'A grade abre. Mira e Tomas continuam nas celas; entre e fale com eles.'},
 {label:'Usar o arame (+1 vigilância).',requires:s=>item(s,'Arame')?null:'Pegue o arame na cozinha.',effect:{suspicion:1,consume:['Arame'],flags:{cellOpen:true,wireUsed:true}},response:'A grade abre; o arame fica preso. Entre na ala para libertar os moradores.'},
 {label:'Aproveitar o intervalo da ronda (+2 vigilância).',requires:s=>s.flags.timing?null:'Observe a ronda na entrada da cozinha.',effect:{suspicion:2,flags:{cellOpen:true,forcedCell:true}},response:'Você impede que a grade feche. O defeito será percebido. Mira e Tomas ainda aguardam dentro das celas.'}
 ]}
};
function act(s){return G.scenes[s.scene]?.act??(G.scenes[s.scene]?.ending?4:0);}
function sideChoices(id,s){return (actions[id]?.choices||[]).filter(c=>!c.once||!s.flags[c.once]).map(c=>({...c,lock:id==='eron'&&s.flags.eronBetrayed?'Eron foi denunciado e não aceita mais ajudar.':id==='tomas'&&s.flags.tomasTransferred?'Tomas já foi transferido. A cela está vazia.':c.requires?.(s)||null}));}
function available(id,s){const a=actions[id];return a&&act(s)>=a.act&&!s.flags.committed&&!G.scenes[s.scene]?.ending&&(!a.done||!s.flags[a.done]);}
function perform(s,id,index){if(!available(id,s))throw Error('Interação indisponível');const c=sideChoices(id,s)[index];if(!c||c.lock)throw Error('Escolha indisponível');const next=JSON.parse(JSON.stringify(s)),e=c.effect||{};for(const k of Object.keys(stats))next[k]=Math.max(0,Math.min(9,next[k]+(e[k]||0)));Object.assign(next.flags,e.flags||{});next.inventory=[...new Set([...next.inventory,...(e.items||[])])].filter(i=>!(e.consume||[]).includes(i));next.history.push({scene:s.scene,title:actions[id].title,choice:c.label,note:c.response});const diff=changes(s,next,e);next.pending=null;if(id==='gate'&&next.suspicion>=7&&(e.suspicion||0)>0){next.scene='captura';return {state:next,text:'A vigilância crítica e o ruído da grade atraem o vigia antes da passagem.',changes:diff};}return {state:next,text:c.response,changes:diff};}
function groupReason(s){return s.flags.eronBetrayed?'Eron foi denunciado e está preso.':!s.flags.rescued?'Mira ainda está presa.':s.eron<2?'Eron ainda não se comprometeu.':!s.flags.escapePlan?'Vocês não combinaram a rota na cozinha.':'Falta confiança de Mira (2) ou o registro assinado.';}
function plan(s){return [
 {done:!!s.flags.rescued,text:'Libertar Mira · grade da ala leste',target:'mira',action:'mira'},
 {done:!!s.flags.tomasRescued,text:s.flags.tomasTransferred?'Tomas transferido · resgate perdido nesta partida':'Libertar Tomas · cela interna (opcional, altera o final)',target:'tomas',action:'tomas'},
 {done:!!s.flags.escapePlan,text:'Combinar a fuga com Eron · cozinha',target:'eronKitchen',action:'eron'},
 {done:!!s.flags.latchOpen,text:'Verificar o trinco com Noah · portão (rota alternativa)',target:'exitLatch',action:'noah'}
 ];}
function relations(s){return [
 ['Mira',s.mira,s.flags.rescued?(s.mira>=2?'Livre, disposta a organizar os moradores.':'Livre; precisa de uma prova para arriscar os demais.'):s.flags.miraTaken?'Presa na ala leste. Abra a grade e fale com ela.':s.mira>=2?'Confia que você não entregará outros nomes.':'Cautelosa; ações concretas importam mais do que promessas.'],
 ['Eron',s.eron,s.flags.eronBetrayed?'Preso após sua denúncia. Não voltará a ajudar nesta partida.':s.flags.escapePlan?'Aliado com uma tarefa e um percurso combinados.':s.eron>=2?'Aceita ajudar. Combine a tarefa antes da fuga.':'Ainda não assumiu o risco. Mostre a requisição ou um compromisso.'],
 ['Noah',s.noah,s.flags.latchOpen?'O trinco foi aberto diante de você.':s.flags.noahTask?'Prometeu abrir o trinco. Falta verificar.':s.flags.confronted?'Foi confrontado sobre as denúncias.':'Proximidade não comprova lealdade. Compare o que ele diz com o que faz.'],
 ['Adultos',s.adults,s.adults>=3?'Seu serviço permite pedir a chave e usar um disfarce.':'Não autorizam a retirada da chave.']
 ];}
const evidence=[['bedClue','Etiqueta T-17','A costura da cama liga Tomas ao número do registro.'],['registerClue','Transferência sem destino','O livro aponta uma caixa na cozinha, não uma viagem.'],['kitchenClue','Requisição da ala leste','Tomas foi retido dentro do orfanato.'],['warning','Aviso de Mira','Ela está na primeira cela; Noah sabia do encontro.'],['altarClue','Código do altar','Sino → chama → raiz.'],['proof','Registro assinado','Prova de transferências registradas antes de acontecerem.'],['transferDelayed','Ordem destruída','O transporte foi atrasado, mas a prova original se perdeu.']];
function consequences(s){const f=s.flags;return [f.escapeSolo?(s.scene==='sobrevivente'?'Você saiu sozinho. Os aliados não receberam seu sinal.':'Você tentou seguir sozinho, mas não alcançou o exterior.'):f.rescued?'Mira saiu da cela e participou da tentativa de fuga.':'Mira continuou presa quando você escolheu seu caminho.',f.tomasRescued?(f.escapeSolo?'Tomas deixou a cela, mas você não confirmou que ele cruzou o portão.':s.scene==='voz'||s.scene==='luz'?'Tomas cruzou o portão com os outros.':'Tomas saiu da cela; a captura de Kali interrompeu o plano de saída.'):(f.tomasTransferred?'Tomas foi transferido para outra unidade.':'Tomas ficou em OldHood.')+(f.transferDelayed?' A ordem destruída atrasou sua transferência.':''),f.proof?(s.scene==='voz'||s.scene==='luz'||s.scene==='sobrevivente'?'O registro saiu com Kali. Há nomes e uma assinatura para uma denúncia.':'O registro foi retomado pelos adultos.'):'A prova assinada não saiu de OldHood.',f.latchOpen?'Noah abriu o trinco diante de Kali. Isso não apagou sua participação nas denúncias.':f.confronted?'Noah foi confrontado, mas não abriu uma saída verificada.':'Noah não precisou responder pelo que contou à Actras.'];}
const endingTexts={voz:['Os primeiros moradores atravessam a porta. Mira conta cada pessoa em voz baixa. Eron confere a curva, volta dois passos e chama quem ainda hesita.','A Actras perde o controle do corredor porque a fuga tem tarefas, uma entrada e uma saída. Kali não precisa inventar um caminho no último instante.'],luz:['Noah segura a porta lateral enquanto Kali, Mira e Eron atravessam. A mudança começou no trinco que ele abriu diante deles.','— Vai. Alguém precisa segurar.\nKali olha para trás. Noah fica para atrasar o vigia. Seu destino permanece desconhecido; a ajuda não apaga as denúncias que levaram Mira à cela.'],sobrevivente:['Kali alcança as árvores e só para quando o sino já parece distante. Está livre.','Sobreviver foi uma escolha. O que fez antes de correr determina quem ainda pode esperar por ajuda e que prova existe fora dos muros.'],traicao:['O vigia fecha a porta. Noah fica do outro lado. Dessa vez, não pode dizer que não percebeu a cadeira nem a câmera.','A investigação termina sob o controle da Actras. A confiança que não exigiu uma ação verificável ofereceu aos adultos a passagem que faltava.'],isolamento:['O ramal termina no depósito de carvão. A porta desenhada na parede não tem maçaneta. Kali se vira e encontra o vigia.','Um percurso poderia ter sido aprendido com Eron. Sem essa preparação, a urgência levou Kali a um lugar que não tinha saída.'],captura:['O cerco fecha antes da passagem. A Actras retoma o corredor e separa Kali de quem poderia ajudá-lo.','A suspeita acumulada, uma porta forçada ou um plano incompleto deixaram uma oportunidade para os vigias. O diário guarda a sequência que levou até aqui.']};
for(const [id,text]of Object.entries(endingTexts)){G.scenes[id].text=text;G.scenes[id].act=4;}
function characterPoint(kind,s){const p=M.positions;if(kind==='mira')return s.flags.rescued?point(46,28.5):s.flags.miraTaken?p.miraCell:p.mira;if(kind==='eron'&&s.flags.eronBetrayed)return point(55,8.5);if(kind==='eron')return s.scene==='desaparecimento'?p.eronDorm:act(s)>=1?p.eronKitchen:p.eronDorm;if(kind==='noah')return ['noah','segredo'].includes(s.scene)?p.noahHall:['emboscada','limiar'].includes(s.scene)?point(42,39.5):s.flags.noahTask&&act(s)>=3?p.exitLatch:p.noahDorm;return null;}
function points(s){return Object.entries(actions).filter(([id])=>available(id,s)&&sideChoices(id,s).length).map(([id,a])=>({...(['mira','eron','noah'].includes(id)?characterPoint(id,s):M.positions[a.target]),id,action:id,name:a.name}));}
M.target=(s,w)=>{if(w?.tracked){const p=points(s).find(p=>p.action===w.tracked);if(p)return {...p,objective:p.name+' · preparação opcional. Use E ao se aproximar.'};}const names={meeting:'Mesa de planejamento',tomasBed:'Cama de Tomas',ledger:'Registro T-17',box:'Caixa T-17',tools:'Caixa de reparos',watch:'Observar a ronda',cellDoor:'Fechadura',keyDesk:'Chave de fita branca',records:'Registro de saída',relic:'Símbolo de Kali',eronKitchen:'Eron',climax:'Líder da Actras',escapeTurn:'Última curva',exit:'Portão',altar:'Base do altar',mira:'Mira',miraCell:'Mira',guardHall:'Vigia',service:'Vigia da cozinha',noahDorm:'Noah',examiner:'Sala de observação',miraBed:'Cama de Mira',bed:'Bilhete de Eron',officeDoor:'Porta entreaberta',eronDorm:'Eron'};const t=M.stages[s.scene];return t?{...M.positions[t[0]],id:t[0],name:names[t[0]]||t[2],objective:t[1]}:null;};
const api={chapters,act,normalize,changes,actions,sideChoices,available,perform,groupReady,noahReady,groupReason,plan,relations,evidence,consequences,characterPoint,points};root.GameAdventure=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
