/* Personalidades, pedidos e itens. O roteiro principal continua em adventure.js. */
(function(root){
'use strict';
const G=root.GameStory||(typeof require==='function'?require('./story.js'):null),M=root.GameWorld||(typeof require==='function'?require('./world.js'):null),A=root.GameAdventure||(typeof require==='function'?require('./adventure.js'):null),D=root.GameDanger||(typeof require==='function'?require('./danger.js'):null);
const names={mira:'Mira',eron:'Eron',noah:'Noah',guard:'Vigias'},stat={mira:'mira',eron:'eron',noah:'noah',guard:'adults'},point=(x,y)=>M.authoredPoint(x,y);
const quests=[
 {id:'mira-book',who:'mira',title:'Entre as páginas',reward:2,request:'Mira olha por cima do seu ombro. — Um livro... na sala de leitura. Atrás da estante da direita. A capa é verde. Pode trazer? Sem falar meu nome.',thanks:'Mira segura o livro contra o peito. — Você não contou para ninguém? Obrigada. Eu marco as páginas em que as pessoas conseguem ir embora. Posso mostrar uma, se quiser.',items:[['Livro de capa verde',36.5,5.8,'livro','As margens guardam pequenas estrelas desenhadas a lápis. Uma frase está marcada: “Ela abriu a janela antes de escolher o caminho.”']]},
 {id:'mira-ribbon',who:'mira',title:'Uma pequena marca',reward:1,request:'Mira espera os passos se afastarem. — Perdi a fita que usava de marcador, perto das camas. Azul, bem fininha. Eu sei que parece pouca coisa... mas era da minha irmã.',thanks:'Ela passa a fita entre os dedos. — Você procurou mesmo. Minha irmã dizia que azul era a cor de quem ainda tinha céu. Nunca contei isso a ninguém aqui.',items:[['Fita azul de Mira',8.3,8.8,'objeto','Uma fita de tecido azul, gasta nas pontas. Há uma pequena flor costurada à mão.']]},
 {id:'mira-notebook',who:'mira',title:'O que eu queria mostrar',reward:2,request:'Mira ainda confere a porta, mas desta vez se aproxima. — Escondi um caderno no canto da sala de leitura. Tem desenhos meus. Antes eu tinha medo de alguém ver. Agora queria que você visse.',thanks:'Mira abre o caderno entre vocês. — Esse é o quintal da minha casa. Essa sou eu... falando sem precisar olhar para trás. Ainda tenho medo, Kali. Só que, com você aqui, consigo terminar as frases.',items:[['Caderno de desenhos',38.5,10.5,'bilhete','Casas, pássaros e janelas abertas. No último desenho, duas pessoas dividem um banco. “Ainda cabe mais alguém”, está escrito no canto.']]},
 {id:'eron-letter',who:'eron',title:'A carta que ficou',reward:2,request:'Eron não levanta a cabeça. — Tomas deixou uma carta no baú do dormitório. Era meu melhor amigo. Sumiu e ninguém explica. A chave foi parar na cozinha. Se achar... traz para mim.',thanks:'Eron demora a abrir a carta. — Ele guardou nosso plano. Achei que só eu lembrava. Obrigado por não dizer que eu precisava esquecer. Não sei conversar muito... mas pode ficar aqui.',items:[['Chave do baú de Tomas',50.5,26.8,'chave','Uma chave curta com a letra T riscada na haste. Abre o baú de Tomas no dormitório.'],['Carta de Tomas',15.3,5.8,'bilhete','“Eron, guarda minha vez no tabuleiro. Se eu me atrasar, não deixa ninguém jogar por mim. Quando sairmos daqui, terminamos a partida.”','Chave do baú de Tomas']]},
 {id:'eron-piece',who:'eron',title:'A última peça',reward:1,request:'Eron olha para o chão do salão. — A gente jogava depois da última refeição. Falta a peça de madeira. Perto dos bancos do fundo. Não quero que varram como se fosse lixo.',thanks:'Ele fecha a peça na mão. — Tomas sempre escolhia essa. Eu reclamava porque ele ganhava. Agora eu deixaria ganhar de novo. Eron olha para você pela primeira vez sem desviar imediatamente.',items:[['Peça do tabuleiro',11.5,38.5,'objeto','Uma peça de madeira entalhada, com um pequeno T na base e marcas de muitas partidas.']]},
 {id:'eron-note',who:'eron',title:'Um nome, não um número',reward:2,request:'— Ouvi que guardam bilhetes confiscados nos arquivos — diz Eron. — Só depois que a passagem estiver aberta. Procura algo com a letra do Tomas? Não é uma promessa de que ele voltou. Eu sei. Só quero saber o que tentou dizer.',thanks:'Eron lê duas vezes. — Ele tentou avisar. Eu fiquei aqui achando que tinha feito alguma coisa errada. Você trouxe uma coisa que é dele, não uma versão dos adultos. Agora me conta como posso ajudar.',items:[['Bilhete confiscado de Tomas',57.5,39.5,'bilhete','“Não pedi transferência. Disseram que eu precisava esperar na ala leste. Se perguntarem por mim, digam ao Eron que não fui embora por vontade própria.”',null,'tunnel']]},
 {id:'noah-list',who:'noah',title:'A lista autorizada',reward:1,request:'— Posso te pedir uma coisa? A lista de presença ficou na observação. O vigia autorizou buscar. Só a folha sobre a mesa, certo? Eu espero aqui perto dele. Assim ninguém precisa perguntar por que sumimos os dois.',thanks:'— Ótimo, é essa mesmo! Você foi e voltou sem problema. Eu já sabia que ia conseguir. Deixa que eu entrego quando ele terminar a ronda. Tem um jeito certo de fazer as coisas por aqui.',items:[['Lista de presença',42.5,38.5,'bilhete','Uma folha de conferência das refeições, carimbada para circulação entre a cozinha e a observação. Não autoriza entrada nas celas.']]},
 {id:'noah-message',who:'noah',title:'Antes da próxima ronda',reward:1,request:'Noah interrompe a frase quando o vigia passa e espera a permissão com um olhar. — Tudo certo. Há um recado na cozinha com o horário da próxima conferência. Traz para mim? Se a porta estiver trancada, não force.',thanks:'— Viu? Era só buscar. Eu confiro os horários porque não gosto de ser pego de surpresa. Você também devia. Se ouvir seu nome na chamada, responde logo. Eu sempre respondo.',items:[['Recado da ronda',37.5,27.5,'bilhete','“Conferência de mantimentos antes do segundo sino. Moradores em serviço devem apresentar a folha ao responsável.”']]},
 {id:'noah-hours',who:'noah',title:'Tudo em seu lugar',reward:2,request:'— O livro de horários voltou para a leitura — Noah explica, sem perder de vista o adulto. — Preciso conferir a cópia. Não é segredo, pode perguntar ao vigia. Eu prefiro quando todo mundo sabe onde eu estou.',thanks:'Noah já começa a folhear. — Obrigado! É mais fácil conversar com você do que ficar repetindo instruções para os outros. Mas, se o vigia chamar, eu vou. Não quero que ache que estou escondendo alguma coisa.',items:[['Livro de horários',38.5,6.5,'livro','Horários de refeições, estudo e serviço. As anotações têm a letra cuidadosa de Noah. Todas as alterações foram rubricadas por um vigia.']]},
 {id:'guard-stock',who:'guard',title:'Conferência de mantimentos',reward:1,request:'— Está sem tarefa? Cozinha. Registro de mantimentos. Traga a folha. Entendeu?',thanks:'— Está completo? O vigia confere a assinatura. — Está. Serviço registrado. Pode ir.',items:[['Registro de mantimentos',47.5,26.8,'bilhete','Contagem de sacos de farinha, azeite e velas. A última linha aguarda a conferência do vigia.']]},
 {id:'guard-key',who:'guard',title:'Uma chave fora do lugar',reward:1,request:'— Viu uma chave de latão no salão? Perto da parede direita. Recolha. Não use. Traga para mim.',thanks:'— Tentou abrir alguma porta? Kali nega. O vigia guarda a chave. — Continue assim.',items:[['Chave da despensa',27.5,30.5,'chave','Chave de latão com a etiqueta “Despensa”. Foi solicitada para devolução, não para abrir a ala restrita.']]},
 {id:'guard-form',who:'guard',title:'Assinar e conferir',reward:1,request:'— Último serviço. Ficha de manutenção, na observação. Leia o local. Confira o selo. Traga sem dobrar.',thanks:'— Local? Observação. Selo? Intacto. O vigia risca a lista. — Três serviços concluídos. Volte à rotina.',items:[['Ficha de manutenção',34.5,38.5,'bilhete','Observação: troca da lâmpada e inspeção da janela. Selo intacto da Actras. Nenhuma autorização adicional consta na ficha.']]}
];
const items={};for(const q of quests)for(const [name,x,y,type,text,needs,lock]of q.items)items[name]={name,...point(x,y),type,text,needs,lock,quest:q.id};
const clone=s=>JSON.parse(JSON.stringify(s));
function normalize(s){const old=s.errands&&typeof s.errands==='object'?s.errands:{};s.errands={};for(const q of quests)if(['active','done'].includes(old[q.id]))s.errands[q.id]=old[q.id];return s;}
const initial=G.initial;G.initial=()=>normalize(initial());const normal=A.normalize;A.normalize=s=>normalize(normal(s));
function status(s,q){normalize(s);return s.errands[q.id]||'available';}
function ownerAvailable(who,s){return !G.scenes[s.scene]?.ending&&!s.flags.committed&&!(who==='eron'&&s.flags.eronBetrayed)&&!(who==='mira'&&s.flags.miraTaken&&!s.flags.rescued);}
function current(who,s){normalize(s);return quests.find(q=>q.who===who&&s.errands[q.id]!=='done');}
function ready(q,s){return q.items.every(([name])=>s.inventory.includes(name));}
function itemLock(item,s,w){return item.needs&&!s.inventory.includes(item.needs)?'Encontre primeiro: '+item.needs:item.lock&&!s.flags[item.lock]&&!(item.lock==='tunnel'&&w?.tunnelOpen)?'Abra a passagem dos arquivos pelo mecanismo do altar.':null;}
function taskPoint(q,s,w){if(ready(q,s))return {...actorPoint(q.who,s,w),id:'talk-'+q.who,person:q.who,name:'Entregar a '+names[q.who]};const item=q.items.map(([name])=>items[name]).find(i=>!s.inventory.includes(i.name));return {...item,id:'pickup-'+q.id,item:item.name,name:'Recolher '+item.name};}
function points(s,w){normalize(s);return quests.filter(q=>s.errands[q.id]==='active'&&ownerAvailable(q.who,s)).flatMap(q=>q.items.map(([name])=>items[name]).filter(i=>!s.inventory.includes(i.name)).map(i=>({...i,id:'pickup-'+i.name,item:i.name,name:(itemLock(i,s,w)?'Examinar ':'Recolher ')+i.name})));}
function perform(s,op,id,world){
 normalize(s);const next=clone(s),q=quests.find(q=>q.id===id||q.items.some(([n])=>n===id));
 if(!q||!ownerAvailable(q.who,s)||s.pending||s.danger?.encounter)return {state:s,error:'Resolva a conversa atual antes deste pedido.'};
 const actual=current(q.who,s);let text='',changes=[],cost=0;
 if(op==='accept'){
  if(actual?.id!==q.id||s.errands[q.id])return {state:s,error:'Este pedido já foi registrado ou ainda não foi liberado.'};
  next.errands[q.id]='active';text='Pedido anotado: '+q.title+'. Você pode acompanhar os passos em Tarefas.';
 }else if(op==='collect'){
  const item=items[id];if(!item||s.errands[q.id]!=='active'||s.inventory.includes(id))return {state:s,error:'Este item não está disponível.'};
  const lock=itemLock(item,s,world);if(lock)return {state:s,error:lock};
  if(!M.canInteract(world.player,item,s,world))return {state:s,error:'Aproxime-se do objeto para recolhê-lo.'};
  next.inventory.push(id);text=item.type==='chave'?'Você recolhe '+id+'.':'Você guarda '+id+' no inventário. Abra a mochila para ler ou examinar.';cost=1;
 }else if(op==='deliver'){
  if(s.errands[q.id]!=='active'||!ready(q,s))return {state:s,error:'Você ainda não recolheu todos os itens deste pedido.'};
  if(!(q.who==='guard'?[actorPoint('guard',s,world),M.positions.examiner,...(s.scene==='confinamento'?[M.positions.guardHall]:[])]:[actorPoint(q.who,s,world)]).some(p=>M.canInteract(world.player,p,s,world,62)))return {state:s,error:'Aproxime-se de '+names[q.who]+' para entregar.'};
  next.errands[q.id]='done';const give=q.items.filter(([n])=>items[n].type!=='chave'||q.who==='guard').map(([n])=>n);
  next.inventory=next.inventory.filter(n=>!give.includes(n));next[stat[q.who]]=Math.min(9,next[stat[q.who]]+q.reward);text=q.thanks;cost=1;
 }else return {state:s,error:'Ação desconhecida.'};
 changes=A.changes(s,next);if(op==='accept')changes.push('Novo pedido: '+q.title);if(op==='deliver')changes.push('Pedido concluído: '+q.title);
 if(cost&&A.act(s)>=3)changes.push(...D.clock(next,1));
 next.history.push({scene:s.scene,title:q.title,choice:op==='accept'?'Aceitar pedido':op==='collect'?'Recolher '+id:'Entregar os itens',note:text});
 return {state:next,text,changes,quest:q};
}
function conversation(who,s){
 const level=s[stat[who]]||0;
 if(who==='mira')return {title:level<2?'Uma voz quase escondida':level<5?'Entre uma olhada e outra':'Agora posso contar',text:s.flags.miraTaken&&!s.flags.rescued?'Mira fala pela grade, os olhos na porta. — Ainda está aí? Por favor... abra a fechadura antes que voltem.':level<2?'Mira recolhe as mãos e confere o corredor duas vezes. — Oi... Melhor falar baixo.\nEla parece esperar um ruído atrás de cada palavra. — Você precisa de alguma coisa?':level<5?'Mira espera a sombra do vigia passar. — Você voltou. Achei que fosse esquecer o que pedi.\nEla se aproxima um pouco. — Eu reparo nas portas. Em quem entra, em quem demora a sair... Só não sei com quem falar disso.':s.flags.rescued?'— Ainda olho para trás — Mira admite. — Mas agora consigo pensar em quem vai andar ao meu lado. Você me ouviu quando eu mal conseguia falar. Quero fazer o mesmo por você.':'— Eu ensaio as conversas antes de dormir — Mira confessa. — Com você, estou começando a não precisar.\nUm passo no corredor a faz parar; depois ela continua. — O medo não sumiu. Só deixou de ocupar todas as palavras.'};
 if(who==='eron')return {title:level<2?'A cadeira vazia':level<5?'Uma lembrança de cada vez':'Quando ele voltar',text:s.flags.eronBetrayed?'Eron se afasta da grade. — Você entregou meu nome. Não tenho outro para te dar.':s.flags.tomasRescued?'Eron respira fundo. — Tomas está fora da cela. Ainda fico esperando alguém dizer que foi engano. Obrigado por procurar quando eu mal conseguia levantar a cabeça.':s.flags.tomasTransferred?'— Levaram ele de novo — Eron diz, olhando para o chão. — Agora pelo menos sabemos que ele não me abandonou. Não fala que vai ficar tudo bem. Só fica um pouco.':level<2?'Eron olha para os próprios sapatos. — Era onde o Tomas sentava. Meu melhor amigo.\nO silêncio se prolonga. — Sumiu. Ninguém explica. Não estou muito... com vontade de conversar.':level<5?'— Ele fazia piada até da sopa — Eron murmura. — Eu fingia que não achava graça.\nEle alisa uma dobra da manga. — Desculpa se demoro para responder. Às vezes começo uma frase e só consigo lembrar que ele não está aqui.':'Eron ergue o rosto. — Se encontrar o Tomas, vou reclamar por ele ter me preocupado. Depois vou abraçar. Nessa ordem.\nUm quase sorriso aparece. — Você não tentou preencher o silêncio com qualquer coisa. Acho que por isso consigo falar agora.'};
 if(who==='noah')return {title:'À vista de todos',text:s.flags.confronted?'Noah acompanha o vigia com os olhos. — Eu sei que conversar bem não resolve o que fiz. Ficar perto deles sempre pareceu a opção segura. Só que era seguro para mim, não para vocês.\n— Se eu prometer alguma coisa agora, pode cobrar que faça.':level<2?'— Ei, Kali! Dormiu bem? Eu lembro quando você chegou. Mostrei onde guardar as coisas, lembra? O horário mudou um pouco, mas eu te explico.\nNoah dá espaço ao vigia e espera que ele passe. — É melhor ficar por aqui. Se chamarem, eu escuto. Nunca deixo um pedido deles para depois.':'— Você já conhece meu jeito: eu falo, confiro o sino, falo mais um pouco — Noah diz. — Não gosto de surpresas.\nEle interrompe a conversa para responder “sim, senhor” ao adulto. — Pronto. Onde estávamos? Ah, sim. Se precisar saber uma regra, pergunta para mim. Eu sigo todas.'};
 return {title:'Perguntas curtas',text:level<3?'O vigia confere suas mãos. — De onde veio? Quem estava com você? Tem autorização?\nEle espera respostas, não explicações.':'— Serviço em dia? Itens devolvidos? O vigia risca uma linha. — Bom. Não mude isso.'};
}
const ambient=G.ambient;G.ambient=(k,s)=>names[k]?conversation(k,s):ambient(k,s);
G.scenes.mira.text=s=>[conversation('mira',s).text,'Mira olha para a porta antes de acrescentar: — O Tomas... não respondeu à chamada. Pergunte ao Noah. Mas não aqui. E não diga que fui eu.'];
G.scenes.desaparecimento.text=s=>[conversation('eron',s).text,s.eron<2?'— Levaram as coisas dele. A caixa foi para a cozinha. Terceira costura do colchão... olha lá.\nEron aperta os dedos. — Depois, o livro de chamadas. T-17. Só isso que eu sei.':'— Vou te contar direito — Eron diz. — Vi levarem a caixa do Tomas para a cozinha. Ele escondia uma etiqueta na terceira costura do colchão. Procure T-17 no livro da leitura depois.\n— Não acredito na transferência. Ele teria me contado.'];
G.scenes.noah.text=s=>[conversation('noah',s).text,'— Tomas? Transferido. É o que está na lista. Para onde? Não cuido dessa parte. Se o vigia disser outra coisa, eu te conto.\nNoah endireita a postura quando as chaves tilintam. Eron espera no dormitório; parece ter ouvido mais do que essa resposta.'];
// Itens de trama continuam sendo obtidos pelas escolhas originais.
const storyItems={'Bilhete de Eron':{type:'bilhete',text:'“Terceira costura do colchão. Não encoste na primeira. É a que eles verificam.”'},'Aviso de Mira':{type:'bilhete',text:'“Me levaram para a primeira cela. Tomas está atrás da divisória. Não aceite a porta aberta que Noah oferecer.”'}};
const take=G.take;G.take=(s,i)=>{const n=take(s,i);for(const [flag,name]of [['bedClue','Bilhete de Eron'],['warning','Aviso de Mira']])if(n.flags[flag]&&!n.inventory.includes(name))n.inventory.push(name);return n;};
function itemInfo(name){return items[name]||storyItems[name]||{name,type:/chave/i.test(name)?'chave':/bilhete|registro|página|etiqueta|requisição/i.test(name)?'bilhete':'objeto',text:'Objeto da investigação. Seu uso aparece nas conversas e no diário.'};}
const targetKinds={mira:'mira',miraCell:'mira',eronDorm:'eron',eronKitchen:'eron',noahDorm:'noah',noahHall:'noah',guardDorm:'guard',guardHall:'guard',service:'guard'};
function storyKind(s){return targetKinds[M.stages[s.scene]?.[0]]||null;}
function actorPoint(kind,s,w){return root.GameResidents?.point(kind,s,w)|| (kind==='guard'?M.positions.guardDorm:A.characterPoint(kind,s));}
const originalPoints=A.points;A.points=(s,w)=>originalPoints(s).map(p=>['mira','eron','noah'].includes(p.action)?{...p,...actorPoint(p.action,s,w)}:p);
const target=M.target;M.target=(s,w)=>{
 if(w?.tracked?.startsWith('errand:')){const q=quests.find(q=>q.id===w.tracked.slice(7));if(q&&status(s,q)!=='done'){const p=status(s,q)==='active'?taskPoint(q,s,w):{...actorPoint(q.who,s,w),id:'talk-'+q.who,person:q.who,name:'Falar com '+names[q.who]};return {...p,objective:q.title+' · '+p.name};}}
 const p=target(s,w);if(!p)return p;
 const kind=p.action&&['mira','eron','noah'].includes(p.action)?p.action:targetKinds[p.id];if(kind){const location=actorPoint(kind,s,w);return {...p,...location,person:kind,objective:'Encontre '+names[kind]+' · '+M.roomAt(location.x,location.y)+'.'};}return p;
};
const api={names,stat,quests,items,normalize,current,ready,status,ownerAvailable,itemLock,taskPoint,points,perform,conversation,itemInfo,actorPoint,storyKind};root.GameSocial=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
