'use strict';
(()=>{
const G=window.GameStory,M=window.GameWorld,A=window.GameAdventure,D=window.GameDanger,S=window.GameSocial,R=window.GameResidents,$=id=>document.getElementById(id),canvas=$('canvas');
const SAVE='dont-believe.topdown.v2',ENDS='dont-believe.endings.v1',PREFS='dont-believe.topdown.preferences';
const renderer=createGameRenderer(canvas,M,(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c;},window.GameArt?.images||{});
let state=G.initial(),world=M.fresh(),guards=M.guards(),playing=false,dialogue=null,keys=new Set(),dpr=1,last=0,saving=0,storageOK=true,walkSinceSave=false,touchSneak=false,soundOn=false,audio=null,gain=null;
let endView=null,endPreview=false,endReturn=null;
let endings=read(ENDS,[]);if(!Array.isArray(endings))endings=[];endings=endings.filter(id=>G.scenes[id]?.ending);
let prefs=read(PREFS,{cones:true,reduced:false});if(!prefs||typeof prefs!=='object')prefs={cones:true,reduced:false};
let saved=read(SAVE,null);if(!validSave(saved))saved=null;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{storageOK=false;return false;}}
function validSave(s){return !!(s&&s.version===2&&s.story&&Object.hasOwn(G.scenes,s.story.scene)&&['adults','mira','eron','noah','suspicion'].every(k=>Number.isFinite(s.story[k])&&s.story[k]>=0&&s.story[k]<=9)&&s.story.flags&&typeof s.story.flags==='object'&&Array.isArray(s.story.history)&&s.story.history.every(h=>h&&typeof h.title==='string'&&typeof h.choice==='string')&&Array.isArray(s.story.inventory)&&s.story.inventory.every(v=>typeof v==='string')&&(!s.story.pending||typeof s.story.pending.text==='string')&&s.world?.player&&Number.isFinite(s.world.player.x)&&Number.isFinite(s.world.player.y));}
function save(){saved={version:2,story:state,world};write(SAVE,saved);$('save-status').textContent=storageOK?'✓ PROGRESSO SALVO':'SALVAMENTO INDISPONÍVEL';walkSinceSave=false;}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls='primary'){const b=element('button',text,cls);b.addEventListener('click',fn);return b;}
function notice(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').hidden=true,4100);}
function clearMovement(){keys.clear();world.player.step=0;}
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(320,Math.round(r.width*dpr));canvas.height=Math.max(300,Math.round(r.height*dpr));}
function objective(){D.normalize(state);S.normalize(state);updateRelationships();$('task-count').textContent=S.quests.filter(q=>state.errands[q.id]==='active').length;$('danger-status').textContent=D.status(state);$('danger-status').hidden=!playing||!!G.scenes[state.scene].ending;const goal=M.target(state,world);$('objective').textContent=goal?.objective||'Suas escolhas chegaram ao fim deste caminho.';$('item-count').textContent=state.inventory.length;$('ending-count').textContent=endings.length+' / 6';$('resume').hidden=!saved;$('chapter-label').textContent=A.chapters[A.act(state)];const clues=A.evidence.filter(([f])=>state.flags[f]).length;$('quest-progress').textContent=world.tracked?'PISTA MARCADA · J para voltar à missão':state.scene==='preparar'?A.plan(state).filter(p=>p.done).length+' / 4 preparações · J para ver as rotas':clues+' pistas conectadas · J diário';const marks=[];if(state.flags.cellOpen)marks.push('Grade aberta');if(state.flags.rescued)marks.push('Mira livre');if(state.flags.tomasRescued)marks.push('Tomas livre');if(state.flags.distracted)marks.push('Ronda desviada');if(state.flags.latchOpen)marks.push('Trinco aberto');$('world-state').textContent=marks.join(' · ');$('world-state').hidden=!marks.length;}
function atHome(){$('relationships').hidden=true;$('danger-status').hidden=true;hideEnding();playing=false;clearMovement();closeDialogue();$('home-screen').hidden=false;$('mission').hidden=true;$('world-state').hidden=true;$('interact-prompt').hidden=true;document.body.classList.add('at-home');$('resume').hidden=!saved;$('ending-count').textContent=endings.length+' / 6';$('location').textContent='O Orfanato';}
function start(){state=G.initial();world=M.fresh();guards=M.guards();save();enter();openStory();}
function newGame(){if(saved){modal('Uma nova história');para('Uma nova partida substitui o progresso 2D atual. Os finais descobertos serão mantidos.');$('modal-content').append(button('CONTINUAR PARTIDA',()=>{closeModal();resume();}),button('INICIAR NOVA PARTIDA',()=>{closeModal();start();}),button('CANCELAR',closeModal,'secondary'));}else start();}
function enter(){hideEnding();playing=true;$('relationships').hidden=false;$('home-screen').hidden=true;$('mission').hidden=false;document.body.classList.remove('at-home');objective();resize();canvas.focus({preventScroll:true});if(G.scenes[state.scene].ending)openStory();}
function resume(){if(!saved)return;state=A.normalize(JSON.parse(JSON.stringify(saved.story)));world=Object.assign(M.fresh(),JSON.parse(JSON.stringify(saved.world)));world.observed=world.observed&&typeof world.observed==='object'&&!Array.isArray(world.observed)?world.observed:{};world.explored=Array.isArray(world.explored)?world.explored:[];world.alert=Math.max(0,Math.min(99,world.alert||0));M.normalizeWorld(world,state);world.player.dir=['up','down','left','right'].includes(world.player.dir)?world.player.dir:'down';world.player.step=Number.isFinite(world.player.step)?world.player.step:0;guards=M.guards();enter();if(state.pending||state.danger.encounter)openStory();}
function pages(texts){const pages=[];let current=[],length=0;for(const paragraph of texts.flatMap(t=>t.split('\n'))){if(length+paragraph.length>360&&current.length){pages.push(current);current=[];length=0;}current.push(paragraph);length+=paragraph.length;}if(current.length)pages.push(current);return pages.length?pages:[['…']];}
function speaker(){const custom=G.scenes[state.scene].speaker;if(custom)return [custom==='guard'?'VIGIA DA ACTRAS':custom==='leader'?'LÍDER DA ACTRAS':custom.toUpperCase(),custom];const id=state.scene;if(['noah','segredo','oferta','limiar','emboscada','questionar','verdade'].includes(id))return ['NOAH','noah'];if(['mira','resgate'].includes(id))return ['MIRA','mira'];if(['desaparecimento','eron'].includes(id))return ['ERON','eron'];if(['quarto','recusa','interrogatorio','confinamento'].includes(id))return ['VIGIA DA ACTRAS','guard'];if(id==='confronto')return ['LÍDER DA ACTRAS','leader'];return ['KALI','kali'];}
function openStory(){if(state.danger?.encounter){openEncounter();return;}const scene=G.scenes[state.scene];clearMovement();if(scene.ending&&!state.pending){if(!endings.includes(state.scene)){endings.push(state.scene);write(ENDS,endings);objective();}showEnding(state.scene);return;}if(state.pending)dialogue={type:'consequence',title:'O eco da sua escolha',pages:pages([state.pending.text]),page:0,note:state.pending.note,changes:state.pending.changes,speaker:['KALI','kali']};else dialogue={type:scene.ending?'ending':'story',title:scene.title,pages:pages(G.value(scene.text,state)),page:0,speaker:speaker()};if(scene.ending&&!state.pending&&!endings.includes(state.scene)){endings.push(state.scene);write(ENDS,endings);objective();}showDialogue();}
function hideEnding(){endView=null;endPreview=false;endReturn=null;$('ending-screen').hidden=true;document.body.classList.remove('at-ending');resize();}
function showEnding(id,preview=false){$('relationships').hidden=true;$('danger-status').hidden=true;const scene=G.scenes[id],theme=window.EndingScreens.themes[id];if(!scene?.ending||!theme)return;if(preview&&!endings.includes(id))return;const back=preview?{id:endView,home:!$('home-screen').hidden}:null;closeDialogue();if($('modal').open)closeModal();clearMovement();endView=id;endPreview=preview;endReturn=back;$('home-screen').hidden=true;$('mission').hidden=true;$('interact-prompt').hidden=true;$('notice').hidden=true;$('world-state').hidden=true;document.body.classList.remove('at-home');document.body.classList.add('at-ending');$('ending-screen').hidden=false;$('ending-screen').style.setProperty('--ending-accent',theme.accent);$('ending-number').textContent='FINAL '+theme.number+' / 06';$('ending-label').textContent=theme.label;$('ending-title').textContent=scene.title;$('ending-quote').textContent='“'+scene.quote+'”';$('ending-story').replaceChildren(...G.value(scene.text,state).flatMap(t=>t.split('\n')).map(t=>element('p',t)));const outcome=preview?read('dont-believe.outcomes.v3',{})[id]:state;$('ending-consequences').replaceChildren(element('small','AS MARCAS DESTA PARTIDA'));if(outcome)A.consequences(outcome).forEach(t=>$('ending-consequences').append(element('p',t)));else $('ending-consequences').append(element('p','Este final foi descoberto numa versão anterior. Uma nova partida registra as consequências detalhadas.'));if(!preview){const records=read('dont-believe.outcomes.v3',{});records[id]=JSON.parse(JSON.stringify(state));write('dont-believe.outcomes.v3',records);}$('ending-discovered').textContent=(preview?'REVISITANDO ESTE FINAL':'CAMINHO CONCLUÍDO')+' · '+endings.length+' DE 6 FINAIS DESCOBERTOS';$('ending-menu').textContent=preview?'VOLTAR À COLEÇÃO':'VOLTAR AO MENU';$('ending-art').setAttribute('aria-label',theme.alt);window.EndingScreens.draw($('ending-art'),id);$('ending-screen').scrollTop=0;$('ending-title').focus({preventScroll:true});resize();}
function leaveEnding(){if(!endPreview){save();atHome();return;}const back=endReturn;hideEnding();if(back?.id)showEnding(back.id);else if(back?.home)atHome();else{$('mission').hidden=!playing;}showEndings();}
function say(title,text,actions=null,who=['KALI','kali']){clearMovement();dialogue={type:'lore',title,pages:pages([text]),page:0,speaker:who,actions};showDialogue();}
function showDialogue(){const d=dialogue;if(!d)return;document.body.classList.add('in-dialogue');$('dialogue').hidden=false;$('interact-prompt').hidden=true;$('dialogue-title').textContent=d.title;$('speaker').textContent=d.speaker[0];$('page-count').textContent=String(d.page+1).padStart(2,'0')+' / '+String(d.pages.length).padStart(2,'0');$('dialogue-text').replaceChildren(...d.pages[d.page].map(t=>element('p',t,t.startsWith('—')?'speech':'')));$('choices').replaceChildren();$('dialogue-note').textContent=d.note||'SUAS ESCOLHAS DEIXAM MARCAS';$('dismiss-dialogue').hidden=d.type==='ending'||d.type==='danger';$('dialogue-extra').hidden=!(d.type==='story'&&['mira','eron','noah'].includes(d.speaker[1]));$('consequence-list').replaceChildren(...(d.changes||[]).map(t=>element('div',t,'consequence-chip')));
paintPortrait(d.speaker[1]);
let list=[];
if(d.page<d.pages.length-1)list=[{label:'Continuar',fn:()=>{d.page++;showDialogue();}}];
else if(d.type==='consequence')list=[{label:'Voltar à exploração',fn:()=>{state.pending=null;closeDialogue();objective();save();if(G.scenes[state.scene].ending)openStory();}}];
else if(d.type==='story')list=G.choices(state).map((c,i)=>({label:c.label,lock:c.requires?.(state),hint:choiceHint(c),fn:()=>select(i)}));
else if(d.type==='ending')list=[{label:'Ver os finais descobertos',fn:showEndings},{label:'Voltar ao menu',fn:()=>{closeDialogue();save();atHome();}}];
else list=d.actions||[{label:'Voltar à exploração',fn:closeDialogue}];
list.forEach((c,i)=>{const b=button('',c.fn,'choice');b.append(element('span',String(i+1).padStart(2,'0')));const text=element('div',c.label);if(c.lock)text.append(element('small',c.lock));else if(c.hint)text.append(element('small',c.hint,'choice-hint'));b.append(text,element('span',c.lock?'—':'↗'));b.disabled=!!c.lock;$('choices').append(b);});
$('dialogue').scrollTop=0;const dialogueCard=document.querySelector('.dialogue-card');if(dialogueCard)dialogueCard.scrollTop=0;$('choices').querySelector('button:not(:disabled)')?.focus({preventScroll:true});}
function paintPortrait(kind){
 const c=$('portrait'),pc=c.getContext('2d'),atlas=window.GameArt?.images.portraits;pc.clearRect(0,0,c.width,c.height);c.setAttribute('aria-label','Retrato de '+(dialogue?.speaker[0]||'Kali'));
 if(window.CharacterSprites?.portrait(pc,c.width,c.height,kind,window.GameArt?.images))return;
 if(atlas){const index=window.GameArt.portraits[kind]??0,cw=atlas.width/3,ch=atlas.height/2;pc.imageSmoothingEnabled=false;pc.drawImage(atlas,(index%3)*cw,Math.floor(index/3)*ch,cw,ch,0,0,c.width,c.height);}
 else{pc.save();pc.scale(c.width/36,c.height/42);renderer.sprite(pc,18,38,kind,'down',0);pc.restore();}
}
function closeDialogue(){if(dialogue?.type==='danger'&&state.danger?.encounter)return;dialogue=null;$('dialogue').hidden=true;document.body.classList.remove('in-dialogue');clearMovement();if(playing)canvas.focus({preventScroll:true});}
function choiceHint(c){const prefix=D.storyCost(state,G.choices(state).indexOf(c))?'Custo: 1 ação do prazo. ':'';const e=G.value(c.effect,state)||{};if((state.scene==='fechadura'||dialogue?.sideId==='gate')&&(e.suspicion||0)+state.suspicion>=7&&e.flags?.cellOpen&&(e.suspicion||0)>0)return 'VIGILÂNCIA CRÍTICA: este método termina em captura. Volte para buscar ajuda ou a chave.';return prefix+(c.hint||c.note||'');}
function select(index){const previous=state.scene;state=G.take(state,index);world.tracked=null;if(state.flags.tunnel)world.tunnelOpen=true;if(previous==='subsolo'&&state.scene==='arquivo'){world.player.x=54*M.T;world.player.y=41.8*M.T;world.player.dir='up';}world.alert=0;closeDialogue();objective();save();if(state.pending||G.scenes[state.scene].ending)openStory();else notice(M.target(state,world)?.objective||'');}

function openEncounter(){clearMovement();const final=state.danger.encounter.kind==='checkpoint';dialogue={type:'danger',title:final?'O cerco do portão':'Pare. Esvazie os bolsos.',pages:pages([final?'O vigia bloqueia a última curva. — O líder deixou você passar. Eu não. Kali precisa sacrificar um recurso ou arriscar o próprio corpo. A preparação ainda pode se desfazer aqui.':'Uma mão prende o ombro de Kali. — Outra vez fora do quarto. O vigia estende a palma. Não existe resposta sem custo. Na próxima detecção após três advertências, ou com vigilância 8, haverá captura.']),page:0,speaker:['VIGIA DA ACTRAS','guard'],note:D.status(state)+' · A revista custa 2 ações do prazo.',actions:D.options(state).map(c=>({...c,fn:()=>{state=D.resolve(state,c.id);closeDialogue();objective();save();openStory();}}))};showDialogue();}

function openSide(id){if(!A.available(id,state)){notice('Esta ação já foi concluída ou a preparação terminou.');return;}const action=A.actions[id],opts=A.sideChoices(id,state);dialogue={type:'lore',sideId:id,title:action.title,pages:pages([G.value(action.text,state)]),page:0,speaker:[action.who.toUpperCase(),action.who],actions:opts.map((c,i)=>({label:c.label,lock:c.lock,hint:((id==='gate')&&(c.effect?.suspicion||0)+state.suspicion>=7&&c.effect?.flags?.cellOpen&&(c.effect?.suspicion||0)>0)?'VIGILÂNCIA CRÍTICA: este método termina em captura.':A.act(state)>=3?'Custo: 1 ação do prazo de Tomas.':null,fn:()=>{const result=A.perform(state,id,i);state=result.state;world.tracked=null;world.alert=0;objective();save();if(G.scenes[state.scene].ending){closeDialogue();openStory();return;}say(action.title,result.text,null,[action.who.toUpperCase(),action.who]);dialogue.changes=result.changes;showDialogue();}})).concat([{label:'Voltar à exploração.',fn:closeDialogue}])};clearMovement();showDialogue();}
function interact(){if(!playing||endView||$('modal').open)return;if(dialogue){const buttons=$('choices').querySelectorAll('button');if(buttons.length===1)buttons[0].click();return;}
if(state.pending||state.danger.encounter){openStory();return;}const nearest=interactionTarget();
if(nearest?.door){const result=M.toggleDoor(nearest.door,state,world,[...renderer.npcs(state,world),...guards]);notice(result.text);if(result.changed)save();return;}
if(nearest?.id==='mel'){say('Mel','Você faz carinho em Mel. Ela não responde, mas gosta de você.',null,['MEL','mel']);$('dialogue-note').textContent='UM MOMENTO DE CALMA';return;}
if(nearest?.item){applyErrand('collect',nearest.item);return;}
if(nearest?.person){openCharacter(nearest.person);return;}
if(nearest?.mission){if(nearest.action)openSide(nearest.action);else openStory();return;}
if(nearest?.action){if(['mira','eron','noah'].includes(nearest.action))openCharacter(nearest.action);else openSide(nearest.action);return;}if(nearest?.id==='altar'){say('O obelisco de ametista','A base tem três discos: sino, chama e raiz. A inscrição está parcialmente escondida pela toalha. A passagem será investigada quando você tiver resolvido como agir diante do confinamento.',[{label:'Observar a arte do altar.',fn:()=>{closeDialogue();modal('O altar da Actras');const img=element('img');img.src=window.GameArt?.urls.altar||'assets/altar-pixel.png';img.alt='Altar gótico com o obelisco de ametista';img.className='altar-image';$('modal-content').append(img);}},{label:'Afastar-se.',fn:closeDialogue}]);}
else if(nearest?.id==='books')say('O livro de chamadas',state.flags.registerClue?'Você já encontrou a linha de Tomas. O diário liga o número T-17 à caixa da cozinha. O código do altar é sino, chama e raiz.':'Um livro de chamadas repousa na estante. Você precisa de um nome ou número para distinguir uma pista entre centenas de linhas.');
else if(nearest?.id==='bed')say('Uma cama, quatro paredes',state.flags.bedClue?'A etiqueta retirada da costura aponta para T-17. O colchão foi recolocado.':'A cama guarda marcas de quem passou por OldHood. Eron pode ajudar a distinguir quais delas são recentes.');
else if(['mira','eron','noah','guard'].includes(nearest?.id))openCharacter(nearest.id);
else notice('Aproxime-se de alguém ou de um marcador. Dourado: missão. Azul: preparação. M abre o mapa.');}
function nearby(){
 const list=[...M.doorPoints(state,world),{...M.melPoint(world),id:'mel',name:'Fazer carinho em Mel'},...S.points(state,world),...A.points(state,world),{...M.positions.altar,id:'altar',name:'Examinar o altar'},{...M.positions.bed,id:'bed',name:'Examinar a cama'},{...M.positions.ledger,id:'books',name:'Examinar os livros'},...renderer.npcs(state,world).filter(n=>['mira','eron','noah','guard'].includes(n.kind)).map(n=>({...n,id:n.kind,person:n.kind,name:'Conversar com '+n.name}))];
 return list.filter(p=>M.canInteract(world.player,p,state,world)).sort((a,b)=>Math.hypot(a.x-world.player.x,a.y-world.player.y)-Math.hypot(b.x-world.player.x,b.y-world.player.y))[0];
}
function interactionTarget(){
 const goal=M.target(state,world),near=nearby(),p=world.player;
 const gd=M.canInteract(p,goal,state,world,62)?Math.hypot(p.x-goal.x,p.y-goal.y):Infinity;
 const nd=near?Math.hypot(p.x-near.x,p.y-near.y):Infinity;
 // Portas e Mel próximas têm prioridade; a mesma escolha alimenta o aviso e E.
 if(near&&(near.door||near.id==='mel')&&nd<=gd+12)return near;
 return gd<62&&gd<=nd+12?{...goal,mission:true}:near;
}
function move(dx,dy){const p=world.player,old={x:p.x,y:p.y};M.move(p,dx,dy,state,world);return p.x!==old.x||p.y!==old.y;}
function update(dt){const p=world.player;let dx=(keys.has('right')?1:0)-(keys.has('left')?1:0),dy=(keys.has('down')?1:0)-(keys.has('up')?1:0);const sneak=keys.has('sneak')||touchSneak;const speed=(sneak?64:128)*(1-state.danger.wounds*.15);if(dx||dy){const len=Math.hypot(dx,dy);const ox=p.x,oy=p.y;if(move(dx/len*speed*dt,dy/len*speed*dt)){p.step+=Math.hypot(p.x-ox,p.y-oy)/20;walkSinceSave=true;}else p.step=0;p.dir=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');}else p.step=0;
if(M.updateMel(state,world,dt))walkSinceSave=true;
if(R.update(state,world,dt))walkSinceSave=true;
renderer.updateActors?.(state,world,dt);
let seen=false;
const activeGuards=guards.filter((g,i)=>!state.flags.distracted||i===0);for(const g of activeGuards){const pace=1+state.suspicion*.035+(state.danger.hunt>0?.7:0);M.updateGuard(g,dt,pace,state,world);const x=p.x-g.x,y=p.y-g.y,distance=Math.hypot(x,y),range=(sneak?64:125)+state.suspicion*(sneak?2:5);g.range=range;const angle=Math.abs(Math.atan2(y,x*g.dir));if(M.night.has(state.scene)&&distance<range&&(distance<24||angle<.5)&&M.visible(g,p,state,world))seen=true;}
state.danger.grace=Math.max(0,state.danger.grace-dt);state.danger.hunt=Math.max(0,(state.danger.hunt||0)-dt);
if(M.night.has(state.scene)&&state.danger.grace<=0)world.alert=Math.max(0,Math.min(100,(world.alert||0)+(seen?(sneak?26:48):-38)*dt));else world.alert=0;
if(world.alert>=100){world.alert=0;state=D.startEncounter(state);objective();save();openStory();}
$('danger-status').textContent=D.status(state)+(state.danger.grace>0?' · RECUAR '+Math.ceil(state.danger.grace)+'s':state.danger.hunt>0?' · RONDA EM ALERTA':'');
$('location').textContent=M.roomAt(p.x,p.y);$('stealth-label').textContent=sneak?'KALI · PASSOS SILENCIOSOS':'KALI · LUZITRUISTA';$('risk-label').textContent=world.alert>15?'SENDO VISTO':state.suspicion>=4?'ALTA':state.suspicion>=2?'ATENTA':'DISCRETA';$('risk-bar').style.width=Math.max(8,world.alert||state.suspicion/9*100)+'%';$('risk-bar').style.background=world.alert>15?'#d79d75':'#d0b77e';
const liveGoal=M.target(state,world);if(liveGoal&&$('objective').textContent!==liveGoal.objective)$('objective').textContent=liveGoal.objective;
const close=interactionTarget();$('interact-prompt').hidden=!close||!!dialogue;if(close)$('near-label').textContent=close.name;
}
function frame(time){const dt=Math.min(.035,(time-last)/1000||0);last=time;if(playing&&!endView&&!dialogue&&!$('modal').open&&!document.hidden){update(dt);saving+=dt;if(saving>2){if(walkSinceSave)save();saving=0;}}const displayState=playing?state:{...G.initial(),scene:'altar'},displayWorld=playing?world:{...M.fresh(),player:{x:16*M.T,y:30*M.T,dir:'up',step:0}};renderer.draw(displayState,displayWorld,guards.filter((g,i)=>!state.flags.distracted||i===0),{time,dpr,cones:prefs.cones,reduced:prefs.reduced,minimap:playing&&innerWidth>700});requestAnimationFrame(frame);}
function modal(title){clearMovement();$('modal-content').replaceChildren(element('h2',title));if(!$('modal').open)$('modal').showModal();}
function closeModal(){$('modal').close();clearMovement();if(playing&&!dialogue)canvas.focus({preventScroll:true});}
function para(text){$('modal-content').append(element('p',text));}
function showMap(){if(!playing)return;modal('Mapa do orfanato');para('Verde: Kali. Dourado: objetivo. Azul: interações de preparação. Vermelho: portas fechadas. A linha respeita as trancas; abra as portas comuns com E ao longo do caminho. Mel aparece em branco na posição atual.');const c=element('canvas');c.width=930;c.height=690;renderer.drawMap(c,state,world);$('modal-content').append(c);para(M.target(state,world)?.objective||'Este caminho chegou ao fim.');}
function entry(title,text,cls='entry'){const e=element('div',undefined,cls);e.append(element('small',title),element('p',text));$('modal-content').append(e);return e;}
function track(id){if(['mira','tomas'].includes(id)&&state.flags.miraTaken&&!state.flags.cellOpen)id='gate';world.tracked=id;closeModal();objective();save();notice('Ponto marcado no mapa. J permite voltar à missão principal.');}
function showJournal(){modal('Diário · '+A.chapters[A.act(state)]);entry('PERIGO PERSISTENTE',D.status(state));entry('PRAZO DE TOMAS','Ao entrar no confinamento: 10 ações. Escolhas e preparações custam 1; revistas custam 2. Caminhar, ler, revisar tarefas e recuar da fechadura são gratuitos. Destruir a ordem concede +3. Ao zerar, Tomas é transferido se ainda estiver preso.');const main=M.stages[state.scene];entry('PRÓXIMO PASSO',main?.[1]||'Este caminho foi concluído.');if(world.tracked)$('modal-content').append(button('VOLTAR AO OBJETIVO PRINCIPAL',()=>{world.tracked=null;closeModal();objective();save();},'secondary'));if(A.act(state)>=3&&!G.scenes[state.scene].ending){entry('PREPARAR ANTES DO CONFRONTO','Você pode voltar aos cômodos até confirmar a saída na mesa de planejamento. As rotas dependem de ações, não só de confiança.');for(const p of A.plan(state)){const e=entry(p.done?'CONCLUÍDO':'PENDENTE',p.text);if(!p.done&&A.available(p.action,state))e.append(button('MARCAR NO MAPA',()=>track(p.action),'track-button'));}entry('ROTA COLETIVA',A.groupReady(state)?'Preparada: Mira livre, Eron aliado, percurso combinado e apoio para reunir moradores.':A.groupReason(state));entry('ROTA DE NOAH',A.noahReady(state)?'Preparada: trinco verificado, Mira livre e Eron aliado.':'Exige verificar o trinco, libertar Mira e ter confiança 2 com Eron.');entry('DISFARCE E FUGA INDIVIDUAL','Disfarce: confiança 3 com adultos e autorização não confiscada. Fugir sozinho: aprender o trajeto com Eron.');}
$('modal-content').append(button('VER PEDIDOS DOS MORADORES',showTasks,'track-button'));
entry('VIGILÂNCIA · '+state.suspicion+' / 9','A suspeita amplia o alcance e a velocidade das rondas. Na próxima detecção com 3 advertências ou vigilância 8, ocorre captura. Resistir com 2 ferimentos também encerra a fuga. Na grade, métodos ruidosos que atingem vigilância 7 capturam; a chave é silenciosa.');
for(const [name,n,text]of A.relations(state))entry(name.toUpperCase()+' · '+n+' / 9',text,'entry relation-entry');
const clues=A.evidence.filter(([f])=>state.flags[f]);entry('PISTAS CONECTADAS',clues.length?'Leia de cima para baixo: cada achado aponta para o próximo.':'As descobertas aparecerão aqui. Eron viu a retirada das coisas de Tomas.');for(const [,title,text]of clues)entry(title.toUpperCase(),text);
if(A.act(state)>=1&&!state.flags.committed){entry('OUTRAS PREPARAÇÕES','Marque um ponto e use E quando chegar até ele.');for(const p of A.points(state,world))$('modal-content').append(button(p.name,()=>track(p.action),'track-button'));}
entry('CONSEQUÊNCIAS RECENTES','Mudanças confirmadas pelas suas ações.');for(const event of (state.events||[]).slice(-8).reverse())entry(event.title.toUpperCase(),event.changes.join(' · '));
entry('CAMINHO PERCORRIDO','Suas decisões em ordem, da chegada ao momento atual.');for(const h of state.history)entry(h.title.toUpperCase(),h.choice+(h.note?' — '+h.note:''));}
function updateRelationships(){
 const panel=$('relationships');panel.replaceChildren();
 for(const [who,label]of Object.entries(S.names)){
  const value=state[S.stat[who]],row=element('div',undefined,'relation-meter');row.dataset.person=who;
  const heading=element('div',undefined,'relation-heading');heading.append(element('span',label),element('b',value+' / 9'));
  const track=element('div',undefined,'relation-track'),bar=element('i');track.setAttribute('role','progressbar');track.setAttribute('aria-label','Relação com '+label);track.setAttribute('aria-valuemin','0');track.setAttribute('aria-valuemax','9');track.setAttribute('aria-valuenow',String(value));bar.style.width=value/9*100+'%';track.append(bar);
  row.append(heading,track,element('small',value>=5?'Confiança forte':value>=2?'Aproximação':'Primeiros contatos'));panel.append(row);
 }
}
function applyErrand(op,id){
 const result=S.perform(state,op,id,world);if(result.error){notice(result.error);return;}
 state=result.state;if(op==='accept')world.tracked='errand:'+result.quest.id;
 if(op==='deliver'&&world.tracked==='errand:'+result.quest.id)world.tracked=null;
 objective();save();say(result.quest.title,result.text,null,[op==='deliver'?S.names[result.quest.who].toUpperCase():'KALI',op==='deliver'?result.quest.who:'kali']);dialogue.changes=result.changes;showDialogue();
}
function openCharacter(who){
 const line=S.conversation(who,state),actions=[],q=S.current(who,state),goal=M.target(state,{...world,tracked:null});
 if(S.storyKind(state)===who&&M.canInteract(world.player,goal,state,world,62))actions.push({label:'Continuar a história: '+G.scenes[state.scene].title,fn:openStory});
 let text=line.text;
 if(q&&S.ownerAvailable(who,state)){
  text+='\n\n'+q.request;
  if(!state.errands[q.id])actions.push({label:'Aceitar pedido: '+q.title,hint:S.names[who]+' +'+q.reward+' ao entregar.',fn:()=>applyErrand('accept',q.id)});
  else if(S.ready(q,state))actions.push({label:'Entregar os itens: '+q.title,hint:S.names[who]+' +'+q.reward+(A.act(state)>=3?' · custa 1 ação do prazo.':''),fn:()=>applyErrand('deliver',q.id)});
  else actions.push({label:'Marcar o próximo passo: '+q.title,fn:()=>{closeDialogue();trackErrand(q.id);}});
 }
 if(['mira','eron','noah'].includes(who)&&A.available(who,state))actions.push({label:'Investigações e preparações',fn:()=>openSide(who)});
 actions.push({label:'Até depois.',fn:closeDialogue});say(line.title,text,actions,[S.names[who].toUpperCase(),who]);
}
function trackErrand(id){world.tracked='errand:'+id;closeModal();objective();save();notice('Pedido marcado. O alvo acompanha o personagem quando ele anda.');}
function showTasks(){
 if(!playing)return;modal('Pedidos dos moradores');para('Aceite o pedido em uma conversa, recolha os itens com E e volte ao personagem para entregar. Cada recompensa só pode ser recebida uma vez.');
 if(A.act(state)>=3)para('O prazo continua valendo: recolher um item ou entregar um pedido custa 1 ação. Ler e marcar locais não gastam ações.');
 for(const [who,name]of Object.entries(S.names)){
  const group=element('section',undefined,'task-group');group.append(element('h3',name));
  const current=S.current(who,state);
  for(const q of S.quests.filter(q=>q.who===who)){
   const status=state.errands[q.id],active=status==='active',done=status==='done',available=current?.id===q.id&&S.ownerAvailable(who,state),card=element('article',undefined,'task-card');
   card.append(element('small',done?'CONCLUÍDO':active?S.ready(q,state)?'PRONTO PARA ENTREGAR':'EM ANDAMENTO':available?'CONVERSE PARA ACEITAR':'PRÓXIMO PEDIDO'),element('h4',q.title),element('p','Relação com '+name+' +'+q.reward));
   if(active){for(const [item]of q.items){const held=state.inventory.includes(item),info=S.items[item],lock=S.itemLock(info,state,world);card.append(element('p',(held?'✓ ':'○ ')+item+(lock&&!held?' — '+lock:''),'task-step'));}}
   if(done)card.append(element('p','Itens entregues. Recompensa recebida.'));
   else if(available)card.append(button(active?'MARCAR PRÓXIMO PASSO':'ENCONTRAR '+name.toUpperCase(),()=>trackErrand(q.id),'track-button'));
   else card.append(element('p',!S.ownerAvailable(who,state)?'Indisponível nesta etapa da história.':'Conclua o pedido anterior para liberar.'));
   group.append(card);
  }
  $('modal-content').append(group);
 }
}
function showInventory(){
 modal('Inventário');para('Bilhetes e livros podem ser lidos aqui. Para entregar itens, aproxime-se de quem fez o pedido.');
 const grid=element('div',undefined,'inventory-grid');$('modal-content').append(grid);
 if(!state.inventory.length){const empty=element('div',undefined,'inventory-empty');empty.append(element('h3','Seus bolsos estão vazios'),element('p','Converse com Mira, Eron, Noah ou um vigia para receber um pedido. Os objetos encontrados ficam guardados aqui.'),button('VER TAREFAS',showTasks,'track-button'));grid.append(empty);return;}
 const uses={'Arame':['Levantar a lingueta da grade; é consumido no uso.','gate'],'Pão':['Entregar a Mira ou usar durante uma revista.','mira'],'Chave da ala leste':['Abre a grade da ala leste.','gate'],'Trajeto de Eron':['Preparar o caminho da fuga.','eron']};
 for(const name of state.inventory){
  const info=S.itemInfo(name),card=element('article',undefined,'inventory-item');card.dataset.type=info.type;card.append(element('small',info.type.toUpperCase()),element('h3',name),element('p',uses[name]?.[0]||info.text));
  if(['bilhete','livro'].includes(info.type))card.append(button('LER',()=>{modal(name);para(info.text);$('modal-content').append(button('VOLTAR AO INVENTÁRIO',showInventory,'secondary'));},'track-button'));
  const q=S.quests.find(q=>q.items.some(([n])=>n===name)&&state.errands[q.id]==='active');if(q)card.append(button('ACOMPANHAR PEDIDO',()=>trackErrand(q.id),'track-button'));
  else if(uses[name]?.[1]&&A.available(uses[name][1],state))card.append(button('MARCAR LOCAL DE USO',()=>track(uses[name][1]),'track-button'));
  grid.append(card);
 }
}
function showEndings(){modal('Seis ecos da mesma história');for(const [i,id]of ['voz','luz','sobrevivente','traicao','isolamento','captura'].entries()){const e=element('div',undefined,'entry'),found=endings.includes(id);e.append(element('small',String(i+1).padStart(2,'0')),element('p',found?G.scenes[id].title:'Final desconhecido'),element('span',found?G.scenes[id].quote:'Suas próximas escolhas podem revelar outro caminho.'));if(found)e.append(button('REVER ESTE FINAL',()=>showEnding(id,true),'secondary'));$('modal-content').append(e);}}
function help(){modal('Como jogar');para('PERIGO PERSISTENTE: revistas custam recursos, aliados ou ferimentos. Após cada revista, recue durante os 12 segundos de proteção. O prazo de Tomas avança por ações; diálogos e leitura ficam pausados.');para('Você controla Kali. Explore com WASD ou as setas. Aproxime-se dos personagens e objetos e pressione E. No celular, use o direcional e o botão Interagir.');para('T abre as tarefas; I abre o inventário. As barras de relação acompanham Mira, Eron, Noah e os vigias. Conclua os pedidos e entregue os itens pessoalmente para ganhar confiança.');para('O marcador dourado indica o objetivo. M abre o mapa com um caminho sugerido. J abre o diário. Durante um diálogo, escolha com 1–9 ou toque nos botões; E ou Espaço avança quando só há uma opção.');para('Use E perto de uma porta para abrir ou fechar. Grades e arquivos exigem os desbloqueios da história. Mel passeia pelo orfanato através das portas abertas. Aproxime-se dela e use E para fazer carinho.');para('Nas cenas noturnas, os vigias patrulham. Evite a área iluminada à frente deles e use Shift (ou Furtivo no celular) para reduzir o alcance em que percebem você. Paredes e móveis bloqueiam a visão. Os vigias param enquanto você lê diálogos.');para('Ser visto inicia uma revista. Depois de 3 advertências, ou com vigilância 8, a próxima detecção encerra a fuga. Resistir causa um ferimento e vigilância +2. Andar furtivamente e esperar a patrulha passar ajuda a evitar isso.');para('O diário (J) liga pistas, mostra relações e marca objetos no mapa. Nos diálogos, Outros assuntos abre ações opcionais: entregar pão, mostrar provas, combinar o plano ou verificar Noah. As mudanças aparecem imediatamente após a escolha. Os itens são usados perto do personagem ou porta correspondente.');para('O progresso e a posição são salvos neste navegador. O jogo funciona sem internet. O novo modo 2D tem um salvamento separado da versão narrativa.');
for(const [key,label]of [['cones','Mostrar campo de visão dos vigias'],['reduced','Reduzir animações']]){const row=element('label',undefined,'settings-row'),input=element('input');input.type='checkbox';input.checked=!!prefs[key];input.addEventListener('change',()=>{prefs[key]=input.checked;write(PREFS,prefs);});row.append(element('span',label),input);$('modal-content').append(row);}para('Ficção de suspense: coerção, perseguição religiosa e perigo envolvendo adolescentes.');}
function pause(){if(!playing){atHome();return;}modal('Uma pausa no silêncio');para('Seu progresso está salvo. A vigilância fica pausada enquanto este menu estiver aberto.');save();$('modal-content').append(button('VOLTAR AO JOGO',closeModal),button('COMO JOGAR E AJUSTES',help,'secondary'),button('VOLTAR AO MENU INICIAL',()=>{closeModal();atHome();},'secondary'));}
async function sound(){try{if(!audio){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error();audio=new AC();gain=audio.createGain();gain.gain.value=0;gain.connect(audio.destination);for(const f of [55,82.41,110]){const osc=audio.createOscillator(),v=audio.createGain();osc.frequency.value=f;v.gain.value=.15;osc.connect(v);v.connect(gain);osc.start();}}await audio.resume();soundOn=!soundOn;gain.gain.setTargetAtTime(soundOn?.15:0,audio.currentTime,.2);$('sound').textContent=soundOn?'SOM ON':'SOM OFF';$('sound').setAttribute('aria-pressed',soundOn);}catch{notice('Áudio indisponível neste navegador.');}}
const directions={KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',ShiftLeft:'sneak',ShiftRight:'sneak'};
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey)return;if($('modal').open)return;if(endView){if(e.code==='Tab'){const buttons=[...$('ending-screen').querySelectorAll('button:not([hidden]):not(:disabled)')];if(buttons.length){e.preventDefault();const i=buttons.indexOf(document.activeElement);buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length].focus();}}if(e.code==='Escape'&&!e.repeat){e.preventDefault();leaveEnding();}return;}if(dialogue){if(e.code==='Tab'){const buttons=[...$('dialogue').querySelectorAll('button:not([hidden]):not(:disabled)')];if(buttons.length){e.preventDefault();const i=buttons.indexOf(document.activeElement);buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length].focus();}return;}if(e.repeat)return;if(e.code==='Escape'&&dialogue.type!=='ending'){e.preventDefault();closeDialogue();return;}if(['KeyE','Space'].includes(e.code)){e.preventDefault();interact();return;}if(/^[1-9]$/.test(e.key)){e.preventDefault();$('choices').querySelectorAll('button')[+e.key-1]?.click();}return;}if(!playing)return;if(directions[e.code]){e.preventDefault();keys.add(directions[e.code]);return;}if(e.repeat)return;if(e.code==='KeyE'||e.code==='Space'){e.preventDefault();interact();}if(e.code==='KeyM'){e.preventDefault();showMap();}if(e.code==='KeyJ')showJournal();if(e.code==='KeyI')showInventory();if(e.code==='KeyT')showTasks();if(e.code==='Escape')pause();});
document.addEventListener('keyup',e=>{if(directions[e.code])keys.delete(directions[e.code]);});window.addEventListener('blur',()=>{clearMovement();if(playing)save();});window.addEventListener('resize',resize);window.addEventListener('pagehide',()=>{if(playing)save();});document.addEventListener('visibilitychange',()=>{clearMovement();if(audio)gain.gain.setTargetAtTime(soundOn&&!document.hidden?.15:0,audio.currentTime,.2);if(document.hidden&&playing)save();});
for(const b of document.querySelectorAll('[data-move]')){const direction=b.dataset.move;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(playing&&!endView&&!dialogue&&!$('modal').open)keys.add(direction);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys.delete(direction));}
$('ending-menu').addEventListener('click',leaveEnding);$('ending-restart').addEventListener('click',newGame);$('ending-collection').addEventListener('click',showEndings);
$('sneak-touch').addEventListener('click',()=>{touchSneak=!touchSneak;$('sneak-touch').setAttribute('aria-pressed',touchSneak);});$('interact-touch').addEventListener('click',interact);$('start').addEventListener('click',newGame);$('resume').addEventListener('click',resume);$('brand').addEventListener('click',pause);$('menu-btn').addEventListener('click',pause);$('map-btn').addEventListener('click',showMap);$('journal').addEventListener('click',showJournal);$('inventory').addEventListener('click',showInventory);$('tasks').addEventListener('click',showTasks);$('endings-btn').addEventListener('click',showEndings);$('chapters').addEventListener('click',()=>{modal('Capítulo único — O Obelisco');para('Explore o orfanato OldHood e encontre a verdade por trás da Actras. Cinco atos, investigação com pistas conectadas, preparações opcionais e seis desfechos com consequências registradas.');$('modal-content').append(button(saved?'CONTINUAR O CAPÍTULO':'COMEÇAR O CAPÍTULO',()=>{closeModal();saved?resume():start();}));});$('options-home').addEventListener('click',help);$('credits').addEventListener('click',()=>{modal('Créditos');para('Pesquisa: Enzo Raphael dos Reis Pessoa.');para('Ideia, História e Arte: Felipe Bertol Schneider.');para('Desenvolvimento: Enzo Raphael dos Reis Pessoa, Felipe Bertol Schneider.');});$('exit-home').addEventListener('click',()=>{modal('Até o próximo sino');para('O progresso já salvo foi mantido. Você pode fechar esta aba ou voltar ao menu.');$('modal-content').append(button('VOLTAR AO MENU',closeModal));});$('help').addEventListener('click',help);$('sound').addEventListener('click',sound);$('close-modal').addEventListener('click',closeModal);$('dismiss-dialogue').addEventListener('click',closeDialogue);$('dialogue-extra').addEventListener('click',()=>{if(dialogue)openCharacter(dialogue.speaker[1]);});$('modal').addEventListener('close',clearMovement);
window.GameArt?.ready.then(()=>{renderer.refreshArt();if(dialogue)paintPortrait(dialogue.speaker[1]);if(endView)window.EndingScreens.draw($('ending-art'),endView);if(window.GameArt.status.failed.length)notice('Algumas artes não carregaram. Extraia o ZIP inteiro antes de abrir index.html.');});resize();atHome();requestAnimationFrame(frame);
})();
